USE migyd_rufem;
DELIMITER $$

							CREATE TRIGGER caso_update BEFORE UPDATE ON migyd_rufem.caso
							FOR EACH ROW
							BEGIN
								SET @marca = NOW();
								SET @accion = 'UPDATE';
								SET @user_name = IF(@user_name is null,SUBSTRING_INDEX(USER(),'@',1),@user_name);
								SET @dir_ip_cliente = IF(@dir_ip_cliente is null,SUBSTRING_INDEX(USER(),'@',-1),@dir_ip_cliente);
							IF NOT (OLD.id_caso <=> NEW.id_caso) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'id_caso',
										registro_id = NEW.id_caso,
										val_old = OLD.id_caso,
										val_new = NEW.id_caso,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.fecha_carga <=> NEW.fecha_carga) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'fecha_carga',
										registro_id = NEW.id_caso,
										val_old = OLD.fecha_carga,
										val_new = NEW.fecha_carga,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.fecha_hecho <=> NEW.fecha_hecho) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'fecha_hecho',
										registro_id = NEW.id_caso,
										val_old = OLD.fecha_hecho,
										val_new = NEW.fecha_hecho,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.fecha_anoticiamiento <=> NEW.fecha_anoticiamiento) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'fecha_anoticiamiento',
										registro_id = NEW.id_caso,
										val_old = OLD.fecha_anoticiamiento,
										val_new = NEW.fecha_anoticiamiento,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.edad <=> NEW.edad) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'edad',
										registro_id = NEW.id_caso,
										val_old = OLD.edad,
										val_new = NEW.edad,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.franja_etaria <=> NEW.franja_etaria) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'franja_etaria',
										registro_id = NEW.id_caso,
										val_old = OLD.franja_etaria,
										val_new = NEW.franja_etaria,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.domicilio <=> NEW.domicilio) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'domicilio',
										registro_id = NEW.id_caso,
										val_old = OLD.domicilio,
										val_new = NEW.domicilio,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.femicidio_vinculado <=> NEW.femicidio_vinculado) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'femicidio_vinculado',
										registro_id = NEW.id_caso,
										val_old = OLD.femicidio_vinculado,
										val_new = NEW.femicidio_vinculado,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.crimen_odio <=> NEW.crimen_odio) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'crimen_odio',
										registro_id = NEW.id_caso,
										val_old = OLD.crimen_odio,
										val_new = NEW.crimen_odio,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.barrio <=> NEW.barrio) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'barrio',
										registro_id = NEW.id_caso,
										val_old = OLD.barrio,
										val_new = NEW.barrio,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.lugar_hecho <=> NEW.lugar_hecho) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'lugar_hecho',
										registro_id = NEW.id_caso,
										val_old = OLD.lugar_hecho,
										val_new = NEW.lugar_hecho,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.tipo_muerte <=> NEW.tipo_muerte) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'tipo_muerte',
										registro_id = NEW.id_caso,
										val_old = OLD.tipo_muerte,
										val_new = NEW.tipo_muerte,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.localidad_id_localidad <=> NEW.localidad_id_localidad) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'localidad_id_localidad',
										registro_id = NEW.id_caso,
										val_old = OLD.localidad_id_localidad,
										val_new = NEW.localidad_id_localidad,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.localidad_id_hecho <=> NEW.localidad_id_hecho) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'localidad_id_hecho',
										registro_id = NEW.id_caso,
										val_old = OLD.localidad_id_hecho,
										val_new = NEW.localidad_id_hecho,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.persona_id_persona <=> NEW.persona_id_persona) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'persona_id_persona',
										registro_id = NEW.id_caso,
										val_old = OLD.persona_id_persona,
										val_new = NEW.persona_id_persona,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.organismo_origen_id_origen <=> NEW.organismo_origen_id_origen) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'organismo_origen_id_origen',
										registro_id = NEW.id_caso,
										val_old = OLD.organismo_origen_id_origen,
										val_new = NEW.organismo_origen_id_origen,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.apenom_agresor <=> NEW.apenom_agresor) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'apenom_agresor',
										registro_id = NEW.id_caso,
										val_old = OLD.apenom_agresor,
										val_new = NEW.apenom_agresor,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.nrodoc_agresor <=> NEW.nrodoc_agresor) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'nrodoc_agresor',
										registro_id = NEW.id_caso,
										val_old = OLD.nrodoc_agresor,
										val_new = NEW.nrodoc_agresor,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.edad_agresor <=> NEW.edad_agresor) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'edad_agresor',
										registro_id = NEW.id_caso,
										val_old = OLD.edad_agresor,
										val_new = NEW.edad_agresor,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.vinculo <=> NEW.vinculo) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'vinculo',
										registro_id = NEW.id_caso,
										val_old = OLD.vinculo,
										val_new = NEW.vinculo,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.lugar_hecho_nomenclador <=> NEW.lugar_hecho_nomenclador) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'lugar_hecho_nomenclador',
										registro_id = NEW.id_caso,
										val_old = OLD.lugar_hecho_nomenclador,
										val_new = NEW.lugar_hecho_nomenclador,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.usuario_carga <=> NEW.usuario_carga) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'caso',
										campo = 'usuario_carga',
										registro_id = NEW.id_caso,
										val_old = OLD.usuario_carga,
										val_new = NEW.usuario_carga,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;
END;
$$
DELIMITER ;


DELIMITER $$

							CREATE TRIGGER caso_insert AFTER INSERT ON migyd_rufem.caso
							FOR EACH ROW
							BEGIN
								SET @marca = NOW();
								SET @accion = 'INSERT';
								SET @user_name = IF(@user_name is null,SUBSTRING_INDEX(USER(),'@',1),@user_name);
								SET @dir_ip_cliente = IF(@dir_ip_cliente is null,SUBSTRING_INDEX(USER(),'@',-1),@dir_ip_cliente);
							INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'id_caso',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.id_caso,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'fecha_carga',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.fecha_carga,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'fecha_hecho',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.fecha_hecho,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'fecha_anoticiamiento',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.fecha_anoticiamiento,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'edad',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.edad,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'franja_etaria',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.franja_etaria,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'domicilio',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.domicilio,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'femicidio_vinculado',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.femicidio_vinculado,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'crimen_odio',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.crimen_odio,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'barrio',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.barrio,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'lugar_hecho',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.lugar_hecho,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'tipo_muerte',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.tipo_muerte,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'localidad_id_localidad',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.localidad_id_localidad,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'localidad_id_hecho',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.localidad_id_hecho,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'persona_id_persona',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.persona_id_persona,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'organismo_origen_id_origen',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.organismo_origen_id_origen,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'apenom_agresor',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.apenom_agresor,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'nrodoc_agresor',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.nrodoc_agresor,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'edad_agresor',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.edad_agresor,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'vinculo',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.vinculo,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'lugar_hecho_nomenclador',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.lugar_hecho_nomenclador,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'usuario_carga',
								registro_id = NEW.id_caso,
								val_old = NULL,
								val_new = NEW.usuario_carga,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;
END;
$$
DELIMITER ;


DELIMITER $$

							CREATE TRIGGER caso_delete BEFORE DELETE ON migyd_rufem.caso
							FOR EACH ROW
							BEGIN
								SET @marca = NOW();
								SET @accion = 'DELETE';
								SET @user_name = IF(@user_name is null,SUBSTRING_INDEX(USER(),'@',1),@user_name);
								SET @dir_ip_cliente = IF(@dir_ip_cliente is null,SUBSTRING_INDEX(USER(),'@',-1),@dir_ip_cliente);
							INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'id_caso',
								registro_id = OLD.id_caso,
								val_old = OLD.id_caso,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'fecha_carga',
								registro_id = OLD.id_caso,
								val_old = OLD.fecha_carga,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'fecha_hecho',
								registro_id = OLD.id_caso,
								val_old = OLD.fecha_hecho,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'fecha_anoticiamiento',
								registro_id = OLD.id_caso,
								val_old = OLD.fecha_anoticiamiento,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'edad',
								registro_id = OLD.id_caso,
								val_old = OLD.edad,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'franja_etaria',
								registro_id = OLD.id_caso,
								val_old = OLD.franja_etaria,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'domicilio',
								registro_id = OLD.id_caso,
								val_old = OLD.domicilio,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'femicidio_vinculado',
								registro_id = OLD.id_caso,
								val_old = OLD.femicidio_vinculado,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'crimen_odio',
								registro_id = OLD.id_caso,
								val_old = OLD.crimen_odio,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'barrio',
								registro_id = OLD.id_caso,
								val_old = OLD.barrio,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'lugar_hecho',
								registro_id = OLD.id_caso,
								val_old = OLD.lugar_hecho,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'tipo_muerte',
								registro_id = OLD.id_caso,
								val_old = OLD.tipo_muerte,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'localidad_id_localidad',
								registro_id = OLD.id_caso,
								val_old = OLD.localidad_id_localidad,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'localidad_id_hecho',
								registro_id = OLD.id_caso,
								val_old = OLD.localidad_id_hecho,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'persona_id_persona',
								registro_id = OLD.id_caso,
								val_old = OLD.persona_id_persona,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'organismo_origen_id_origen',
								registro_id = OLD.id_caso,
								val_old = OLD.organismo_origen_id_origen,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'apenom_agresor',
								registro_id = OLD.id_caso,
								val_old = OLD.apenom_agresor,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'nrodoc_agresor',
								registro_id = OLD.id_caso,
								val_old = OLD.nrodoc_agresor,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'edad_agresor',
								registro_id = OLD.id_caso,
								val_old = OLD.edad_agresor,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'vinculo',
								registro_id = OLD.id_caso,
								val_old = OLD.vinculo,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'lugar_hecho_nomenclador',
								registro_id = OLD.id_caso,
								val_old = OLD.lugar_hecho_nomenclador,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'caso',
								campo = 'usuario_carga',
								registro_id = OLD.id_caso,
								val_old = OLD.usuario_carga,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;
END;
$$
DELIMITER ;
