USE smgyd_suimvm;
DELIMITER $$

							CREATE TRIGGER sddnayf_new_update BEFORE UPDATE ON smgyd_suimvm.sddnayf_new
							FOR EACH ROW
							BEGIN
								SET @marca = NOW();
								SET @accion = 'UPDATE';
								SET @user_name = IF(@user_name is null,SUBSTRING_INDEX(USER(),'@',1),@user_name);
								SET @dir_ip_cliente = IF(@dir_ip_cliente is null,SUBSTRING_INDEX(USER(),'@',-1),@dir_ip_cliente);
							IF NOT (OLD.id <=> NEW.id) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'sddnayf_new',
										campo = 'id',
										registro_id = NEW.id,
										val_old = OLD.id,
										val_new = NEW.id,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sddnayf_1a <=> NEW.sddnayf_1a) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'sddnayf_new',
										campo = 'sddnayf_1a',
										registro_id = NEW.id,
										val_old = OLD.sddnayf_1a,
										val_new = NEW.sddnayf_1a,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sddnayf_1d <=> NEW.sddnayf_1d) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'sddnayf_new',
										campo = 'sddnayf_1d',
										registro_id = NEW.id,
										val_old = OLD.sddnayf_1d,
										val_new = NEW.sddnayf_1d,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sddnayf_1fa <=> NEW.sddnayf_1fa) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'sddnayf_new',
										campo = 'sddnayf_1fa',
										registro_id = NEW.id,
										val_old = OLD.sddnayf_1fa,
										val_new = NEW.sddnayf_1fa,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sddnayf_1fb <=> NEW.sddnayf_1fb) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'sddnayf_new',
										campo = 'sddnayf_1fb',
										registro_id = NEW.id,
										val_old = OLD.sddnayf_1fb,
										val_new = NEW.sddnayf_1fb,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sddnayf_1g <=> NEW.sddnayf_1g) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'sddnayf_new',
										campo = 'sddnayf_1g',
										registro_id = NEW.id,
										val_old = OLD.sddnayf_1g,
										val_new = NEW.sddnayf_1g,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sddnayf_1h <=> NEW.sddnayf_1h) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'sddnayf_new',
										campo = 'sddnayf_1h',
										registro_id = NEW.id,
										val_old = OLD.sddnayf_1h,
										val_new = NEW.sddnayf_1h,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sddnayf_1i <=> NEW.sddnayf_1i) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'sddnayf_new',
										campo = 'sddnayf_1i',
										registro_id = NEW.id,
										val_old = OLD.sddnayf_1i,
										val_new = NEW.sddnayf_1i,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sddnayf_2a <=> NEW.sddnayf_2a) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'sddnayf_new',
										campo = 'sddnayf_2a',
										registro_id = NEW.id,
										val_old = OLD.sddnayf_2a,
										val_new = NEW.sddnayf_2a,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sddnayf_2d <=> NEW.sddnayf_2d) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'sddnayf_new',
										campo = 'sddnayf_2d',
										registro_id = NEW.id,
										val_old = OLD.sddnayf_2d,
										val_new = NEW.sddnayf_2d,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sddnayf_2fa <=> NEW.sddnayf_2fa) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'sddnayf_new',
										campo = 'sddnayf_2fa',
										registro_id = NEW.id,
										val_old = OLD.sddnayf_2fa,
										val_new = NEW.sddnayf_2fa,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sddnayf_2fb <=> NEW.sddnayf_2fb) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'sddnayf_new',
										campo = 'sddnayf_2fb',
										registro_id = NEW.id,
										val_old = OLD.sddnayf_2fb,
										val_new = NEW.sddnayf_2fb,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sddnayf_2g <=> NEW.sddnayf_2g) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'sddnayf_new',
										campo = 'sddnayf_2g',
										registro_id = NEW.id,
										val_old = OLD.sddnayf_2g,
										val_new = NEW.sddnayf_2g,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sddnayf_2h <=> NEW.sddnayf_2h) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'sddnayf_new',
										campo = 'sddnayf_2h',
										registro_id = NEW.id,
										val_old = OLD.sddnayf_2h,
										val_new = NEW.sddnayf_2h,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sddnayf_2i <=> NEW.sddnayf_2i) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'sddnayf_new',
										campo = 'sddnayf_2i',
										registro_id = NEW.id,
										val_old = OLD.sddnayf_2i,
										val_new = NEW.sddnayf_2i,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caso_id_caso <=> NEW.caso_id_caso) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'sddnayf_new',
										campo = 'caso_id_caso',
										registro_id = NEW.id,
										val_old = OLD.caso_id_caso,
										val_new = NEW.caso_id_caso,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.fechacarga <=> NEW.fechacarga) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'sddnayf_new',
										campo = 'fechacarga',
										registro_id = NEW.id,
										val_old = OLD.fechacarga,
										val_new = NEW.fechacarga,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.usuariocarga <=> NEW.usuariocarga) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'sddnayf_new',
										campo = 'usuariocarga',
										registro_id = NEW.id,
										val_old = OLD.usuariocarga,
										val_new = NEW.usuariocarga,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;
END;
$$
DELIMITER ;


DELIMITER $$

							CREATE TRIGGER sddnayf_new_insert AFTER INSERT ON smgyd_suimvm.sddnayf_new
							FOR EACH ROW
							BEGIN
								SET @marca = NOW();
								SET @accion = 'INSERT';
								SET @user_name = IF(@user_name is null,SUBSTRING_INDEX(USER(),'@',1),@user_name);
								SET @dir_ip_cliente = IF(@dir_ip_cliente is null,SUBSTRING_INDEX(USER(),'@',-1),@dir_ip_cliente);
							INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'id',
								registro_id = NEW.id,
								val_old = NULL,
								val_new = NEW.id,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_1a',
								registro_id = NEW.id,
								val_old = NULL,
								val_new = NEW.sddnayf_1a,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_1d',
								registro_id = NEW.id,
								val_old = NULL,
								val_new = NEW.sddnayf_1d,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_1fa',
								registro_id = NEW.id,
								val_old = NULL,
								val_new = NEW.sddnayf_1fa,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_1fb',
								registro_id = NEW.id,
								val_old = NULL,
								val_new = NEW.sddnayf_1fb,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_1g',
								registro_id = NEW.id,
								val_old = NULL,
								val_new = NEW.sddnayf_1g,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_1h',
								registro_id = NEW.id,
								val_old = NULL,
								val_new = NEW.sddnayf_1h,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_1i',
								registro_id = NEW.id,
								val_old = NULL,
								val_new = NEW.sddnayf_1i,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_2a',
								registro_id = NEW.id,
								val_old = NULL,
								val_new = NEW.sddnayf_2a,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_2d',
								registro_id = NEW.id,
								val_old = NULL,
								val_new = NEW.sddnayf_2d,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_2fa',
								registro_id = NEW.id,
								val_old = NULL,
								val_new = NEW.sddnayf_2fa,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_2fb',
								registro_id = NEW.id,
								val_old = NULL,
								val_new = NEW.sddnayf_2fb,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_2g',
								registro_id = NEW.id,
								val_old = NULL,
								val_new = NEW.sddnayf_2g,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_2h',
								registro_id = NEW.id,
								val_old = NULL,
								val_new = NEW.sddnayf_2h,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_2i',
								registro_id = NEW.id,
								val_old = NULL,
								val_new = NEW.sddnayf_2i,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'caso_id_caso',
								registro_id = NEW.id,
								val_old = NULL,
								val_new = NEW.caso_id_caso,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'fechacarga',
								registro_id = NEW.id,
								val_old = NULL,
								val_new = NEW.fechacarga,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'usuariocarga',
								registro_id = NEW.id,
								val_old = NULL,
								val_new = NEW.usuariocarga,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;
END;
$$
DELIMITER ;


DELIMITER $$

							CREATE TRIGGER sddnayf_new_delete BEFORE DELETE ON smgyd_suimvm.sddnayf_new
							FOR EACH ROW
							BEGIN
								SET @marca = NOW();
								SET @accion = 'DELETE';
								SET @user_name = IF(@user_name is null,SUBSTRING_INDEX(USER(),'@',1),@user_name);
								SET @dir_ip_cliente = IF(@dir_ip_cliente is null,SUBSTRING_INDEX(USER(),'@',-1),@dir_ip_cliente);
							INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'id',
								registro_id = OLD.id,
								val_old = OLD.id,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_1a',
								registro_id = OLD.id,
								val_old = OLD.sddnayf_1a,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_1d',
								registro_id = OLD.id,
								val_old = OLD.sddnayf_1d,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_1fa',
								registro_id = OLD.id,
								val_old = OLD.sddnayf_1fa,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_1fb',
								registro_id = OLD.id,
								val_old = OLD.sddnayf_1fb,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_1g',
								registro_id = OLD.id,
								val_old = OLD.sddnayf_1g,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_1h',
								registro_id = OLD.id,
								val_old = OLD.sddnayf_1h,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_1i',
								registro_id = OLD.id,
								val_old = OLD.sddnayf_1i,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_2a',
								registro_id = OLD.id,
								val_old = OLD.sddnayf_2a,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_2d',
								registro_id = OLD.id,
								val_old = OLD.sddnayf_2d,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_2fa',
								registro_id = OLD.id,
								val_old = OLD.sddnayf_2fa,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_2fb',
								registro_id = OLD.id,
								val_old = OLD.sddnayf_2fb,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_2g',
								registro_id = OLD.id,
								val_old = OLD.sddnayf_2g,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_2h',
								registro_id = OLD.id,
								val_old = OLD.sddnayf_2h,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'sddnayf_2i',
								registro_id = OLD.id,
								val_old = OLD.sddnayf_2i,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'caso_id_caso',
								registro_id = OLD.id,
								val_old = OLD.caso_id_caso,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'fechacarga',
								registro_id = OLD.id,
								val_old = OLD.fechacarga,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'sddnayf_new',
								campo = 'usuariocarga',
								registro_id = OLD.id,
								val_old = OLD.usuariocarga,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;
END;
$$
DELIMITER ;
