USE migyd_rufem;
DELIMITER $$

							CREATE TRIGGER mpa_update BEFORE UPDATE ON migyd_rufem.mpa
							FOR EACH ROW
							BEGIN
								SET @marca = NOW();
								SET @accion = 'UPDATE';
								SET @user_name = IF(@user_name is null,SUBSTRING_INDEX(USER(),'@',1),@user_name);
								SET @dir_ip_cliente = IF(@dir_ip_cliente is null,SUBSTRING_INDEX(USER(),'@',-1),@dir_ip_cliente);
							IF NOT (OLD.id_mpa <=> NEW.id_mpa) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'id_mpa',
										registro_id = NEW.id_mpa,
										val_old = OLD.id_mpa,
										val_new = NEW.id_mpa,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_1 <=> NEW.mpa_1) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_1',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_1,
										val_new = NEW.mpa_1,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_2 <=> NEW.mpa_2) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_2',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_2,
										val_new = NEW.mpa_2,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_3 <=> NEW.mpa_3) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_3',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_3,
										val_new = NEW.mpa_3,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_3a <=> NEW.mpa_3a) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_3a',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_3a,
										val_new = NEW.mpa_3a,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_3a1 <=> NEW.mpa_3a1) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_3a1',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_3a1,
										val_new = NEW.mpa_3a1,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_3b <=> NEW.mpa_3b) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_3b',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_3b,
										val_new = NEW.mpa_3b,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_3b1 <=> NEW.mpa_3b1) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_3b1',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_3b1,
										val_new = NEW.mpa_3b1,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_4 <=> NEW.mpa_4) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_4',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_4,
										val_new = NEW.mpa_4,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_5 <=> NEW.mpa_5) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_5',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_5,
										val_new = NEW.mpa_5,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_6 <=> NEW.mpa_6) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_6',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_6,
										val_new = NEW.mpa_6,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_6a <=> NEW.mpa_6a) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_6a',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_6a,
										val_new = NEW.mpa_6a,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_6b <=> NEW.mpa_6b) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_6b',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_6b,
										val_new = NEW.mpa_6b,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_6c <=> NEW.mpa_6c) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_6c',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_6c,
										val_new = NEW.mpa_6c,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_7 <=> NEW.mpa_7) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_7',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_7,
										val_new = NEW.mpa_7,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_7a <=> NEW.mpa_7a) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_7a',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_7a,
										val_new = NEW.mpa_7a,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_8 <=> NEW.mpa_8) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_8',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_8,
										val_new = NEW.mpa_8,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_9a <=> NEW.mpa_9a) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_9a',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_9a,
										val_new = NEW.mpa_9a,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_9b <=> NEW.mpa_9b) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_9b',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_9b,
										val_new = NEW.mpa_9b,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_9c <=> NEW.mpa_9c) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_9c',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_9c,
										val_new = NEW.mpa_9c,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_9d <=> NEW.mpa_9d) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_9d',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_9d,
										val_new = NEW.mpa_9d,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_9e <=> NEW.mpa_9e) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_9e',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_9e,
										val_new = NEW.mpa_9e,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_9f <=> NEW.mpa_9f) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_9f',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_9f,
										val_new = NEW.mpa_9f,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_9g <=> NEW.mpa_9g) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_9g',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_9g,
										val_new = NEW.mpa_9g,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_9h <=> NEW.mpa_9h) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_9h',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_9h,
										val_new = NEW.mpa_9h,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_9ha <=> NEW.mpa_9ha) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_9ha',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_9ha,
										val_new = NEW.mpa_9ha,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_10 <=> NEW.mpa_10) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_10',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_10,
										val_new = NEW.mpa_10,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_11 <=> NEW.mpa_11) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_11',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_11,
										val_new = NEW.mpa_11,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_12 <=> NEW.mpa_12) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_12',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_12,
										val_new = NEW.mpa_12,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_13 <=> NEW.mpa_13) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_13',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_13,
										val_new = NEW.mpa_13,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_13a <=> NEW.mpa_13a) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_13a',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_13a,
										val_new = NEW.mpa_13a,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_14 <=> NEW.mpa_14) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_14',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_14,
										val_new = NEW.mpa_14,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.mpa_15 <=> NEW.mpa_15) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'mpa_15',
										registro_id = NEW.id_mpa,
										val_old = OLD.mpa_15,
										val_new = NEW.mpa_15,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caso_id_caso <=> NEW.caso_id_caso) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'caso_id_caso',
										registro_id = NEW.id_mpa,
										val_old = OLD.caso_id_caso,
										val_new = NEW.caso_id_caso,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.fecha_carga <=> NEW.fecha_carga) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'fecha_carga',
										registro_id = NEW.id_mpa,
										val_old = OLD.fecha_carga,
										val_new = NEW.fecha_carga,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.usuario_carga <=> NEW.usuario_carga) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'mpa',
										campo = 'usuario_carga',
										registro_id = NEW.id_mpa,
										val_old = OLD.usuario_carga,
										val_new = NEW.usuario_carga,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;
END;
$$
DELIMITER ;


DELIMITER $$

							CREATE TRIGGER mpa_insert AFTER INSERT ON migyd_rufem.mpa
							FOR EACH ROW
							BEGIN
								SET @marca = NOW();
								SET @accion = 'INSERT';
								SET @user_name = IF(@user_name is null,SUBSTRING_INDEX(USER(),'@',1),@user_name);
								SET @dir_ip_cliente = IF(@dir_ip_cliente is null,SUBSTRING_INDEX(USER(),'@',-1),@dir_ip_cliente);
							INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'id_mpa',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.id_mpa,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_1',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_1,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_2',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_2,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_3',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_3,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_3a',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_3a,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_3a1',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_3a1,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_3b',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_3b,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_3b1',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_3b1,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_4',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_4,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_5',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_5,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_6',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_6,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_6a',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_6a,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_6b',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_6b,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_6c',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_6c,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_7',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_7,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_7a',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_7a,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_8',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_8,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_9a',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_9a,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_9b',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_9b,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_9c',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_9c,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_9d',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_9d,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_9e',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_9e,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_9f',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_9f,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_9g',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_9g,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_9h',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_9h,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_9ha',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_9ha,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_10',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_10,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_11',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_11,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_12',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_12,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_13',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_13,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_13a',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_13a,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_14',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_14,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_15',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.mpa_15,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'caso_id_caso',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.caso_id_caso,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'fecha_carga',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.fecha_carga,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'usuario_carga',
								registro_id = NEW.id_mpa,
								val_old = NULL,
								val_new = NEW.usuario_carga,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;
END;
$$
DELIMITER ;


DELIMITER $$

							CREATE TRIGGER mpa_delete BEFORE DELETE ON migyd_rufem.mpa
							FOR EACH ROW
							BEGIN
								SET @marca = NOW();
								SET @accion = 'DELETE';
								SET @user_name = IF(@user_name is null,SUBSTRING_INDEX(USER(),'@',1),@user_name);
								SET @dir_ip_cliente = IF(@dir_ip_cliente is null,SUBSTRING_INDEX(USER(),'@',-1),@dir_ip_cliente);
							INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'id_mpa',
								registro_id = OLD.id_mpa,
								val_old = OLD.id_mpa,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_1',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_1,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_2',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_2,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_3',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_3,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_3a',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_3a,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_3a1',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_3a1,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_3b',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_3b,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_3b1',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_3b1,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_4',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_4,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_5',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_5,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_6',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_6,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_6a',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_6a,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_6b',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_6b,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_6c',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_6c,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_7',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_7,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_7a',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_7a,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_8',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_8,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_9a',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_9a,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_9b',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_9b,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_9c',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_9c,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_9d',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_9d,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_9e',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_9e,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_9f',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_9f,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_9g',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_9g,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_9h',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_9h,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_9ha',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_9ha,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_10',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_10,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_11',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_11,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_12',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_12,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_13',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_13,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_13a',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_13a,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_14',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_14,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'mpa_15',
								registro_id = OLD.id_mpa,
								val_old = OLD.mpa_15,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'caso_id_caso',
								registro_id = OLD.id_mpa,
								val_old = OLD.caso_id_caso,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'fecha_carga',
								registro_id = OLD.id_mpa,
								val_old = OLD.fecha_carga,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'mpa',
								campo = 'usuario_carga',
								registro_id = OLD.id_mpa,
								val_old = OLD.usuario_carga,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;
END;
$$
DELIMITER ;
