USE migyd_rufem;
DELIMITER $$

							CREATE TRIGGER sdh_update BEFORE UPDATE ON migyd_rufem.sdh
							FOR EACH ROW
							BEGIN
								SET @marca = NOW();
								SET @accion = 'UPDATE';
								SET @user_name = IF(@user_name is null,SUBSTRING_INDEX(USER(),'@',1),@user_name);
								SET @dir_ip_cliente = IF(@dir_ip_cliente is null,SUBSTRING_INDEX(USER(),'@',-1),@dir_ip_cliente);
							IF NOT (OLD.id_sdh <=> NEW.id_sdh) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'id_sdh',
										registro_id = NEW.id_sdh,
										val_old = OLD.id_sdh,
										val_new = NEW.id_sdh,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_1_1 <=> NEW.sdh_1_1) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_1_1',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_1_1,
										val_new = NEW.sdh_1_1,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_1_9 <=> NEW.sdh_1_9) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_1_9',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_1_9,
										val_new = NEW.sdh_1_9,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_1_10 <=> NEW.sdh_1_10) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_1_10',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_1_10,
										val_new = NEW.sdh_1_10,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_1_2_id_nomenclador <=> NEW.sdh_1_2_id_nomenclador) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_1_2_id_nomenclador',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_1_2_id_nomenclador,
										val_new = NEW.sdh_1_2_id_nomenclador,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_1_3 <=> NEW.sdh_1_3) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_1_3',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_1_3,
										val_new = NEW.sdh_1_3,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_1_4 <=> NEW.sdh_1_4) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_1_4',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_1_4,
										val_new = NEW.sdh_1_4,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_1_5_id_nomenclador <=> NEW.sdh_1_5_id_nomenclador) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_1_5_id_nomenclador',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_1_5_id_nomenclador,
										val_new = NEW.sdh_1_5_id_nomenclador,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_1_6_id_nomenclador <=> NEW.sdh_1_6_id_nomenclador) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_1_6_id_nomenclador',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_1_6_id_nomenclador,
										val_new = NEW.sdh_1_6_id_nomenclador,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_1_7 <=> NEW.sdh_1_7) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_1_7',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_1_7,
										val_new = NEW.sdh_1_7,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_1_8 <=> NEW.sdh_1_8) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_1_8',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_1_8,
										val_new = NEW.sdh_1_8,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_2_1 <=> NEW.sdh_2_1) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_2_1',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_2_1,
										val_new = NEW.sdh_2_1,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_2_2_id_nomenclador <=> NEW.sdh_2_2_id_nomenclador) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_2_2_id_nomenclador',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_2_2_id_nomenclador,
										val_new = NEW.sdh_2_2_id_nomenclador,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_2_3 <=> NEW.sdh_2_3) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_2_3',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_2_3,
										val_new = NEW.sdh_2_3,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_2_4 <=> NEW.sdh_2_4) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_2_4',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_2_4,
										val_new = NEW.sdh_2_4,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_3_1 <=> NEW.sdh_3_1) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_3_1',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_3_1,
										val_new = NEW.sdh_3_1,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_3_2 <=> NEW.sdh_3_2) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_3_2',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_3_2,
										val_new = NEW.sdh_3_2,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_3_3_id_nomenclador <=> NEW.sdh_3_3_id_nomenclador) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_3_3_id_nomenclador',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_3_3_id_nomenclador,
										val_new = NEW.sdh_3_3_id_nomenclador,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_3_4_id_nomenclador <=> NEW.sdh_3_4_id_nomenclador) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_3_4_id_nomenclador',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_3_4_id_nomenclador,
										val_new = NEW.sdh_3_4_id_nomenclador,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_4_1 <=> NEW.sdh_4_1) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_4_1',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_4_1,
										val_new = NEW.sdh_4_1,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_4_2 <=> NEW.sdh_4_2) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_4_2',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_4_2,
										val_new = NEW.sdh_4_2,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_4_3 <=> NEW.sdh_4_3) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_4_3',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_4_3,
										val_new = NEW.sdh_4_3,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_5_1a <=> NEW.sdh_5_1a) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_5_1a',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_5_1a,
										val_new = NEW.sdh_5_1a,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_5_1b <=> NEW.sdh_5_1b) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_5_1b',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_5_1b,
										val_new = NEW.sdh_5_1b,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_5_2a <=> NEW.sdh_5_2a) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_5_2a',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_5_2a,
										val_new = NEW.sdh_5_2a,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.sdh_5_2b <=> NEW.sdh_5_2b) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'sdh_5_2b',
										registro_id = NEW.id_sdh,
										val_old = OLD.sdh_5_2b,
										val_new = NEW.sdh_5_2b,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caso_id_caso <=> NEW.caso_id_caso) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'caso_id_caso',
										registro_id = NEW.id_sdh,
										val_old = OLD.caso_id_caso,
										val_new = NEW.caso_id_caso,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.fecha_carga <=> NEW.fecha_carga) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'fecha_carga',
										registro_id = NEW.id_sdh,
										val_old = OLD.fecha_carga,
										val_new = NEW.fecha_carga,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.usuario_carga <=> NEW.usuario_carga) THEN
								INSERT INTO migyd_rufem_auditoria SET
										accion = @accion,
										tabla = 'sdh',
										campo = 'usuario_carga',
										registro_id = NEW.id_sdh,
										val_old = OLD.usuario_carga,
										val_new = NEW.usuario_carga,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;
END;
$$
DELIMITER ;


DELIMITER $$

							CREATE TRIGGER sdh_insert AFTER INSERT ON migyd_rufem.sdh
							FOR EACH ROW
							BEGIN
								SET @marca = NOW();
								SET @accion = 'INSERT';
								SET @user_name = IF(@user_name is null,SUBSTRING_INDEX(USER(),'@',1),@user_name);
								SET @dir_ip_cliente = IF(@dir_ip_cliente is null,SUBSTRING_INDEX(USER(),'@',-1),@dir_ip_cliente);
							INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'id_sdh',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.id_sdh,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_1_1',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_1_1,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_1_9',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_1_9,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_1_10',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_1_10,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_1_2_id_nomenclador',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_1_2_id_nomenclador,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_1_3',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_1_3,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_1_4',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_1_4,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_1_5_id_nomenclador',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_1_5_id_nomenclador,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_1_6_id_nomenclador',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_1_6_id_nomenclador,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_1_7',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_1_7,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_1_8',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_1_8,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_2_1',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_2_1,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_2_2_id_nomenclador',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_2_2_id_nomenclador,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_2_3',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_2_3,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_2_4',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_2_4,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_3_1',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_3_1,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_3_2',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_3_2,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_3_3_id_nomenclador',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_3_3_id_nomenclador,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_3_4_id_nomenclador',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_3_4_id_nomenclador,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_4_1',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_4_1,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_4_2',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_4_2,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_4_3',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_4_3,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_5_1a',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_5_1a,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_5_1b',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_5_1b,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_5_2a',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_5_2a,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_5_2b',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.sdh_5_2b,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'caso_id_caso',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.caso_id_caso,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'fecha_carga',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.fecha_carga,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'usuario_carga',
								registro_id = NEW.id_sdh,
								val_old = NULL,
								val_new = NEW.usuario_carga,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;
END;
$$
DELIMITER ;


DELIMITER $$

							CREATE TRIGGER sdh_delete BEFORE DELETE ON migyd_rufem.sdh
							FOR EACH ROW
							BEGIN
								SET @marca = NOW();
								SET @accion = 'DELETE';
								SET @user_name = IF(@user_name is null,SUBSTRING_INDEX(USER(),'@',1),@user_name);
								SET @dir_ip_cliente = IF(@dir_ip_cliente is null,SUBSTRING_INDEX(USER(),'@',-1),@dir_ip_cliente);
							INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'id_sdh',
								registro_id = OLD.id_sdh,
								val_old = OLD.id_sdh,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_1_1',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_1_1,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_1_9',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_1_9,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_1_10',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_1_10,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_1_2_id_nomenclador',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_1_2_id_nomenclador,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_1_3',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_1_3,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_1_4',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_1_4,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_1_5_id_nomenclador',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_1_5_id_nomenclador,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_1_6_id_nomenclador',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_1_6_id_nomenclador,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_1_7',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_1_7,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_1_8',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_1_8,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_2_1',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_2_1,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_2_2_id_nomenclador',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_2_2_id_nomenclador,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_2_3',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_2_3,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_2_4',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_2_4,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_3_1',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_3_1,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_3_2',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_3_2,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_3_3_id_nomenclador',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_3_3_id_nomenclador,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_3_4_id_nomenclador',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_3_4_id_nomenclador,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_4_1',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_4_1,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_4_2',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_4_2,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_4_3',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_4_3,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_5_1a',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_5_1a,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_5_1b',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_5_1b,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_5_2a',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_5_2a,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'sdh_5_2b',
								registro_id = OLD.id_sdh,
								val_old = OLD.sdh_5_2b,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'caso_id_caso',
								registro_id = OLD.id_sdh,
								val_old = OLD.caso_id_caso,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'fecha_carga',
								registro_id = OLD.id_sdh,
								val_old = OLD.fecha_carga,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO migyd_rufem_auditoria SET
								accion = @accion,
								tabla = 'sdh',
								campo = 'usuario_carga',
								registro_id = OLD.id_sdh,
								val_old = OLD.usuario_carga,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;
END;
$$
DELIMITER ;
