USE smgyd_suimvm;
DELIMITER $$

							CREATE TRIGGER caj_update BEFORE UPDATE ON smgyd_suimvm.caj
							FOR EACH ROW
							BEGIN
								SET @marca = NOW();
								SET @accion = 'UPDATE';
								SET @user_name = IF(@user_name is null,SUBSTRING_INDEX(USER(),'@',1),@user_name);
								SET @dir_ip_cliente = IF(@dir_ip_cliente is null,SUBSTRING_INDEX(USER(),'@',-1),@dir_ip_cliente);
							IF NOT (OLD.id_caj <=> NEW.id_caj) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'id_caj',
										registro_id = NEW.id_caj,
										val_old = OLD.id_caj,
										val_new = NEW.id_caj,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_1a <=> NEW.caj_1a) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_1a',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_1a,
										val_new = NEW.caj_1a,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_1b <=> NEW.caj_1b) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_1b',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_1b,
										val_new = NEW.caj_1b,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_1c <=> NEW.caj_1c) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_1c',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_1c,
										val_new = NEW.caj_1c,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_1d <=> NEW.caj_1d) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_1d',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_1d,
										val_new = NEW.caj_1d,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_2a <=> NEW.caj_2a) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_2a',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_2a,
										val_new = NEW.caj_2a,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_2b <=> NEW.caj_2b) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_2b',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_2b,
										val_new = NEW.caj_2b,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_2c <=> NEW.caj_2c) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_2c',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_2c,
										val_new = NEW.caj_2c,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_2d <=> NEW.caj_2d) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_2d',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_2d,
										val_new = NEW.caj_2d,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_2e <=> NEW.caj_2e) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_2e',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_2e,
										val_new = NEW.caj_2e,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_2f <=> NEW.caj_2f) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_2f',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_2f,
										val_new = NEW.caj_2f,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_3a <=> NEW.caj_3a) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_3a',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_3a,
										val_new = NEW.caj_3a,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_3b <=> NEW.caj_3b) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_3b',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_3b,
										val_new = NEW.caj_3b,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_3c <=> NEW.caj_3c) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_3c',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_3c,
										val_new = NEW.caj_3c,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_3d <=> NEW.caj_3d) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_3d',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_3d,
										val_new = NEW.caj_3d,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_3e <=> NEW.caj_3e) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_3e',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_3e,
										val_new = NEW.caj_3e,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_3f <=> NEW.caj_3f) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_3f',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_3f,
										val_new = NEW.caj_3f,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_3g <=> NEW.caj_3g) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_3g',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_3g,
										val_new = NEW.caj_3g,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_3h <=> NEW.caj_3h) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_3h',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_3h,
										val_new = NEW.caj_3h,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_4a <=> NEW.caj_4a) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_4a',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_4a,
										val_new = NEW.caj_4a,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_4b <=> NEW.caj_4b) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_4b',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_4b,
										val_new = NEW.caj_4b,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_4c <=> NEW.caj_4c) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_4c',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_4c,
										val_new = NEW.caj_4c,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_3i <=> NEW.caj_3i) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_3i',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_3i,
										val_new = NEW.caj_3i,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caj_3j <=> NEW.caj_3j) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caj_3j',
										registro_id = NEW.id_caj,
										val_old = OLD.caj_3j,
										val_new = NEW.caj_3j,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.caso_id_caso <=> NEW.caso_id_caso) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'caso_id_caso',
										registro_id = NEW.id_caj,
										val_old = OLD.caso_id_caso,
										val_new = NEW.caso_id_caso,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.fecha_carga <=> NEW.fecha_carga) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'fecha_carga',
										registro_id = NEW.id_caj,
										val_old = OLD.fecha_carga,
										val_new = NEW.fecha_carga,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;IF NOT (OLD.usuario_carga <=> NEW.usuario_carga) THEN
								INSERT INTO suimvm_auditoria SET
										accion = @accion,
										tabla = 'caj',
										campo = 'usuario_carga',
										registro_id = NEW.id_caj,
										val_old = OLD.usuario_carga,
										val_new = NEW.usuario_carga,
										usuario = @user_name,
										dir_ip = @dir_ip_cliente,
										marca =  @marca;
								END IF;
END;
$$
DELIMITER ;


DELIMITER $$

							CREATE TRIGGER caj_insert AFTER INSERT ON smgyd_suimvm.caj
							FOR EACH ROW
							BEGIN
								SET @marca = NOW();
								SET @accion = 'INSERT';
								SET @user_name = IF(@user_name is null,SUBSTRING_INDEX(USER(),'@',1),@user_name);
								SET @dir_ip_cliente = IF(@dir_ip_cliente is null,SUBSTRING_INDEX(USER(),'@',-1),@dir_ip_cliente);
							INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'id_caj',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.id_caj,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_1a',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_1a,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_1b',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_1b,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_1c',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_1c,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_1d',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_1d,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_2a',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_2a,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_2b',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_2b,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_2c',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_2c,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_2d',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_2d,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_2e',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_2e,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_2f',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_2f,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_3a',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_3a,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_3b',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_3b,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_3c',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_3c,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_3d',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_3d,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_3e',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_3e,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_3f',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_3f,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_3g',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_3g,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_3h',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_3h,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_4a',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_4a,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_4b',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_4b,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_4c',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_4c,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_3i',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_3i,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_3j',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caj_3j,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caso_id_caso',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.caso_id_caso,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'fecha_carga',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.fecha_carga,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'usuario_carga',
								registro_id = NEW.id_caj,
								val_old = NULL,
								val_new = NEW.usuario_carga,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;
END;
$$
DELIMITER ;


DELIMITER $$

							CREATE TRIGGER caj_delete BEFORE DELETE ON smgyd_suimvm.caj
							FOR EACH ROW
							BEGIN
								SET @marca = NOW();
								SET @accion = 'DELETE';
								SET @user_name = IF(@user_name is null,SUBSTRING_INDEX(USER(),'@',1),@user_name);
								SET @dir_ip_cliente = IF(@dir_ip_cliente is null,SUBSTRING_INDEX(USER(),'@',-1),@dir_ip_cliente);
							INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'id_caj',
								registro_id = OLD.id_caj,
								val_old = OLD.id_caj,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_1a',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_1a,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_1b',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_1b,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_1c',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_1c,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_1d',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_1d,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_2a',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_2a,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_2b',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_2b,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_2c',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_2c,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_2d',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_2d,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_2e',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_2e,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_2f',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_2f,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_3a',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_3a,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_3b',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_3b,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_3c',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_3c,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_3d',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_3d,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_3e',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_3e,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_3f',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_3f,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_3g',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_3g,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_3h',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_3h,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_4a',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_4a,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_4b',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_4b,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_4c',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_4c,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_3i',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_3i,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caj_3j',
								registro_id = OLD.id_caj,
								val_old = OLD.caj_3j,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'caso_id_caso',
								registro_id = OLD.id_caj,
								val_old = OLD.caso_id_caso,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'fecha_carga',
								registro_id = OLD.id_caj,
								val_old = OLD.fecha_carga,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;INSERT INTO suimvm_auditoria SET
								accion = @accion,
								tabla = 'caj',
								campo = 'usuario_carga',
								registro_id = OLD.id_caj,
								val_old = OLD.usuario_carga,
								val_new = NULL,
								usuario = @user_name,
								dir_ip = @dir_ip_cliente,
								marca =  @marca;
END;
$$
DELIMITER ;
