-- MySQL Script generated by MySQL Workbench
-- mar 25 feb 2025 13:07:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema smgyd_suimvm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smgyd_suimvm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smgyd_suimvm` ;
USE `smgyd_suimvm` ;

-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`localidad` (
  `id_localidad` INT NOT NULL AUTO_INCREMENT,
  `localidad` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_localidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `nrodoc` VARCHAR(8) NULL,
  `sexo` ENUM("F", "M", "No binario") NULL,
  `genero_autop` ENUM("Mujer Cis", "Mujer Trans", "No binario", "No especificado") NULL,
  `nacionalidad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`organismo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`organismo` (
  `id_organismo` INT NOT NULL AUTO_INCREMENT,
  `nombre_organismo` VARCHAR(45) NOT NULL,
  `referente` VARCHAR(45) NULL,
  `domicilio` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `localidad_id_localidad` INT NOT NULL,
  PRIMARY KEY (`id_organismo`),
  INDEX `fk_organismo_localidad1_idx` (`localidad_id_localidad` ASC) VISIBLE,
  CONSTRAINT `fk_organismo_localidad1`
    FOREIGN KEY (`localidad_id_localidad`)
    REFERENCES `smgyd_suimvm`.`localidad` (`id_localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`organismo_origen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`organismo_origen` (
  `id_origen` INT NOT NULL AUTO_INCREMENT,
  `organismo_id_organismo` INT NOT NULL,
  INDEX `fk_organismo_origen_organismo1_idx` (`organismo_id_organismo` ASC) VISIBLE,
  PRIMARY KEY (`id_origen`),
  CONSTRAINT `fk_organismo_origen_organismo1`
    FOREIGN KEY (`organismo_id_organismo`)
    REFERENCES `smgyd_suimvm`.`organismo` (`id_organismo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`caso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`caso` (
  `id_caso` INT NOT NULL AUTO_INCREMENT,
  `fecha_carga` DATETIME NOT NULL,
  `fecha_anoticiamiento` DATETIME NOT NULL,
  `franja_etaria` ENUM("0-12 años", "13-17 años", "18-29 años", "30-39 años", "40-49 años", "50-59 años", "60 años o más") NULL,
  `domicilio` VARCHAR(255) NULL,
  `femicidio_vinculado` ENUM("Si", "No") NULL COMMENT 'Presuntamente se trata de un femicidio vinculado',
  `crimen_odio` ENUM("Si", "No") NULL COMMENT 'Presuntamente se trata de un crimen de odio o discriminación por orientación sexual o indentidad de género',
  `barrio_hecho` VARCHAR(150) NULL,
  `tipo_muerte` ENUM("Muerte violenta por intervención de un tercero", "Suicidio", "Muerte dudosa") NULL,
  `localidad_id_localidad` INT NOT NULL,
  `localidad_id_hecho` INT NULL,
  `persona_id_persona` INT NOT NULL,
  `organismo_origen_id_origen` INT NOT NULL,
  PRIMARY KEY (`id_caso`),
  INDEX `fk_caso_localidad_idx` (`localidad_id_localidad` ASC) VISIBLE,
  INDEX `fk_caso_localidad1_idx` (`localidad_id_hecho` ASC) VISIBLE,
  INDEX `fk_caso_persona1_idx` (`persona_id_persona` ASC) VISIBLE,
  INDEX `fk_caso_organismo_origen1_idx` (`organismo_origen_id_origen` ASC) VISIBLE,
  CONSTRAINT `fk_caso_localidad`
    FOREIGN KEY (`localidad_id_localidad`)
    REFERENCES `smgyd_suimvm`.`localidad` (`id_localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caso_localidad1`
    FOREIGN KEY (`localidad_id_hecho`)
    REFERENCES `smgyd_suimvm`.`localidad` (`id_localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caso_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `smgyd_suimvm`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caso_organismo_origen1`
    FOREIGN KEY (`organismo_origen_id_origen`)
    REFERENCES `smgyd_suimvm`.`organismo_origen` (`id_origen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`nomencladora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`nomencladora` (
  `id_nomenclador` INT NOT NULL AUTO_INCREMENT,
  `nomenclador` VARCHAR(45) NOT NULL,
  `valor_nomenclador` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_nomenclador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`smgyd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`smgyd` (
  `id_smgyd` INT NOT NULL AUTO_INCREMENT,
  `smgyd_1` ENUM("Si", "No", "En proceso") NULL,
  `smgyd_2` ENUM("Si", "No", "En proceso") NULL,
  `smgyd_3` TEXT NULL,
  `smgyd_4` ENUM("Si", "No", "En proceso") NULL,
  `smgyd_5` ENUM("Si", "No") NULL,
  `smgyd_6` TEXT NULL,
  `smgyd_7_id_nomenclador` INT NULL,
  `smgyd_8_id_nomenclador` INT NULL,
  `smgyd_9` ENUM("Trabajo formal", "Trabajo informal") NULL,
  `smgyd_10` ENUM("Si", "No") NULL,
  `smgyd_11` VARCHAR(255) NULL,
  `smgyd_12` VARCHAR(150) NULL,
  `smgyd_13_id_nomenclador` INT NULL,
  `smgyd_14_id_nomenclador` INT NULL,
  `smgyd_15_id_nomenclador` INT NULL,
  `smgyd_16` ENUM("Si", "No", "No especificado") NULL,
  `smgyd_17` ENUM("Si", "No", "Desconocido") NULL,
  `smgyd_18` TEXT NULL,
  `smgyd_19` ENUM("Si", "No", "No especificado") NULL,
  `smgyd_20` ENUM("Si", "No", "Desconocido") NULL,
  `smgyd_21_id_nomenclador` INT NULL,
  `smgyd_22` ENUM("Si", "No", "No especificado") NULL,
  `smgyd_23` TEXT NULL,
  `smgyd_24` TEXT NULL,
  `caso_id_caso` INT NOT NULL,
  PRIMARY KEY (`id_smgyd`),
  INDEX `fk_smgyd_caso1_idx` (`caso_id_caso` ASC) VISIBLE,
  INDEX `fk_smgyd_nomencladora1_idx` (`smgyd_7_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_smgyd_nomencladora2_idx` (`smgyd_8_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_smgyd_nomencladora3_idx` (`smgyd_13_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_smgyd_nomencladora4_idx` (`smgyd_14_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_smgyd_nomencladora5_idx` (`smgyd_15_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_smgyd_nomencladora6_idx` (`smgyd_21_id_nomenclador` ASC) VISIBLE,
  CONSTRAINT `fk_smgyd_caso1`
    FOREIGN KEY (`caso_id_caso`)
    REFERENCES `smgyd_suimvm`.`caso` (`id_caso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_smgyd_nomencladora1`
    FOREIGN KEY (`smgyd_7_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_smgyd_nomencladora2`
    FOREIGN KEY (`smgyd_8_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_smgyd_nomencladora3`
    FOREIGN KEY (`smgyd_13_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_smgyd_nomencladora4`
    FOREIGN KEY (`smgyd_14_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_smgyd_nomencladora5`
    FOREIGN KEY (`smgyd_15_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_smgyd_nomencladora6`
    FOREIGN KEY (`smgyd_21_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`mpa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`mpa` (
  `id_mpa` INT NOT NULL AUTO_INCREMENT,
  `mpa_1` DATETIME NULL,
  `mpa_2` TIME NULL,
  `mpa_3_id_nomenclador` INT NULL,
  `mpa_4` TEXT NULL,
  `mpa_5_id_nomenclador` INT NULL,
  `mpa_6` ENUM("Si", "No") NULL,
  `mpa_7a` VARCHAR(45) NULL,
  `mpa_7b` INT NULL,
  `mpc_7c_id_nomenclador` INT NULL,
  `mpa_7d` ENUM("Si", "No") NULL,
  `mpa_7e` ENUM("Si", "No") NULL,
  `mpa_7f` ENUM("Si", "No") NULL,
  `mpa_7g` ENUM("Si", "No") NULL,
  `mpa_7h` ENUM("Si", "No") NULL,
  `mpa_7i` TEXT NULL,
  `mpa_8` ENUM("Víctima", "Familia de la víctima") NULL,
  `mpa_9_id_nomenclador` INT NULL,
  `mpa_10` VARCHAR(45) NULL,
  `mpa_11` ENUM("Si", "No", "Tentativa") NULL,
  `mpa_12_id_nomenclador` INT NULL,
  `mpa_13` ENUM("Si", "No", "No especificado") NULL,
  `mpa_13_1a1_id_nomenclador` INT NULL,
  `mpa_13_1a3_id_nomenclador` INT NULL,
  `mpa_13_1a4_id_nomenclador` INT NULL,
  `mpa_13_1b1_id_nomenclador` INT NULL,
  `mpa_13_1b2_id_nomenclador` INT NULL,
  `mpa_13_1b3` ENUM("Si", "No", "No especificado") NULL,
  `mpa_13_1c1` ENUM("Si", "No") NULL,
  `mpa_13_1c2_id_nomenclador` INT NULL,
  `mpa_13_1c3` ENUM("Si", "No") NULL,
  `mpa_13_1c4` TEXT NULL,
  `mpa_13_1d1_id_nomenclador` INT NULL,
  `mpa_13_1d2` ENUM("Si", "No", "No especificado") NULL,
  `mpa_13_1d3` ENUM("Si", "No") NULL,
  `mpa_13_1d4_id_nomenclador` INT NULL,
  `mpa_13_1d5_id_nomenclador` INT NULL,
  `mpa_13_1d6` ENUM("Si", "No") NULL,
  `mpa_13_1d6a` TEXT NULL,
  `mpa_13_1d7` TEXT NULL,
  `mpa_13_1d8` TEXT NULL,
  `mpa_14_1` ENUM("Si", "No") NULL,
  `mpa_14_2_id_nomenclador` INT NULL,
  `mpa_14_3` ENUM("Si", "No", "Desconocido") NULL,
  `mpa_14_4` TEXT NULL,
  `mpa_15_1` ENUM("Si", "No") NULL,
  `mpa_15_2` ENUM("Si", "No") NULL,
  `mpa_15_3` ENUM("Si", "No") NULL,
  `mpa_15_4` ENUM("Si", "No", "No especificado") NULL,
  `mpa_16_1` ENUM("Si", "No") NULL,
  `mpa_16_2` TEXT NULL,
  `mpa_16_3` ENUM("Si", "No") NULL,
  `mpa_17_1` ENUM("Si", "No") NULL,
  `mpa_17_2` ENUM("Si", "No") NULL,
  `mpa_17_3` ENUM("Si", "No") NULL,
  `mpa_18_1` ENUM("Si", "No") NULL,
  `mpa_18_2` ENUM("Si", "No", "Parcial") NULL,
  `mpa_18_3` TEXT NULL,
  `mpa_18_4` TEXT NULL,
  `mpa_19_1` ENUM("Si", "No", "En proceso", "Apelacion en curso", "Caso archivado") NULL,
  `mpa_19_2` DATETIME NULL,
  `mpa_19_3_id_nomenclador` INT NULL,
  `mpa_19_4` TEXT NULL,
  `mpa_19_5_id_nomenclador` INT NULL,
  `mpa_19_6` ENUM("Si", "No", "En proceso") NULL,
  `mpa_19_7_id_nomenclador` INT NULL,
  `caso_id_caso` INT NOT NULL,
  PRIMARY KEY (`id_mpa`),
  INDEX `fk_mpa_nomencladora1_idx` (`mpa_3_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mpa_nomencladora2_idx` (`mpa_5_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mpa_nomencladora3_idx` (`mpc_7c_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mpa_nomencladora4_idx` (`mpa_9_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mpa_nomencladora5_idx` (`mpa_12_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mpa_nomencladora6_idx` (`mpa_13_1a1_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mpa_nomencladora7_idx` (`mpa_13_1a3_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mpa_nomencladora8_idx` (`mpa_13_1a4_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mpa_nomencladora9_idx` (`mpa_13_1b1_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mpa_nomencladora10_idx` (`mpa_13_1b2_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mpa_nomencladora11_idx` (`mpa_13_1c2_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mpa_nomencladora12_idx` (`mpa_13_1d1_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mpa_nomencladora13_idx` (`mpa_13_1d4_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mpa_nomencladora14_idx` (`mpa_13_1d5_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mpa_nomencladora15_idx` (`mpa_14_2_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mpa_nomencladora16_idx` (`mpa_19_3_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mpa_nomencladora17_idx` (`mpa_19_5_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mpa_nomencladora18_idx` (`mpa_19_7_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mpa_caso1_idx` (`caso_id_caso` ASC) VISIBLE,
  CONSTRAINT `fk_mpa_nomencladora1`
    FOREIGN KEY (`mpa_3_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mpa_nomencladora2`
    FOREIGN KEY (`mpa_5_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mpa_nomencladora3`
    FOREIGN KEY (`mpc_7c_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mpa_nomencladora4`
    FOREIGN KEY (`mpa_9_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mpa_nomencladora5`
    FOREIGN KEY (`mpa_12_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mpa_nomencladora6`
    FOREIGN KEY (`mpa_13_1a1_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mpa_nomencladora7`
    FOREIGN KEY (`mpa_13_1a3_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mpa_nomencladora8`
    FOREIGN KEY (`mpa_13_1a4_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mpa_nomencladora9`
    FOREIGN KEY (`mpa_13_1b1_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mpa_nomencladora10`
    FOREIGN KEY (`mpa_13_1b2_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mpa_nomencladora11`
    FOREIGN KEY (`mpa_13_1c2_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mpa_nomencladora12`
    FOREIGN KEY (`mpa_13_1d1_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mpa_nomencladora13`
    FOREIGN KEY (`mpa_13_1d4_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mpa_nomencladora14`
    FOREIGN KEY (`mpa_13_1d5_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mpa_nomencladora15`
    FOREIGN KEY (`mpa_14_2_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mpa_nomencladora16`
    FOREIGN KEY (`mpa_19_3_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mpa_nomencladora17`
    FOREIGN KEY (`mpa_19_5_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mpa_nomencladora18`
    FOREIGN KEY (`mpa_19_7_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mpa_caso1`
    FOREIGN KEY (`caso_id_caso`)
    REFERENCES `smgyd_suimvm`.`caso` (`id_caso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'nomencladora_id_nomenclador';


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`ms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`ms` (
  `id_ms` INT NOT NULL AUTO_INCREMENT,
  `ms_1_1` ENUM("Si", "No") NULL,
  `ms_1_2` DATE NULL,
  `ms_1_3_id_nomenclador` INT NULL,
  `ms_1_4_id_nomenclador` INT NULL,
  `ms_1_5` ENUM("Si", "No") NULL,
  `ms_1_6` TEXT NULL,
  `ms_2_2` TEXT NULL,
  `ms_2_3a_id_nomenclador` INT NULL,
  `ms_2_3b` ENUM("Semanal", "Mensual", "Alerta ante nuevas consultas") NULL,
  `ms_3_1` ENUM("Si", "No") NULL,
  `ms_3_2_id_nomenclador` INT NULL,
  `ms_4_1` ENUM("Si", "No") NULL,
  `ms_4_2_id_nomenclador` INT NULL,
  `ms_4_3a` ENUM("Semanal", "Mensual", "A solicitud") NULL,
  `ms_4_3b_id_nomenclador` INT NULL,
  `ms_5_1` ENUM("Bajo", "Moderado", "Alto") NULL,
  `ms_5_2` ENUM("Lesiones físicas recurrentes", "Antecedentes de consulta por ansiedad y depresión", "Sospecha de abuso o coacción") NULL,
  `ms_5_3` ENUM("Asistencia psicológica de urgencia", "Derivación a refugio", "Acompañamiento de trabajo social especializado") NULL,
  `ms_5_4a` ENUM("Si", "No") NULL,
  `ms_5_4b` ENUM("Intervención conjunta", "Derivación formalizada") NULL,
  `caso_id_caso` INT NOT NULL,
  PRIMARY KEY (`id_ms`),
  INDEX `fk_ms_nomencladora1_idx` (`ms_1_3_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_ms_nomencladora2_idx` (`ms_1_4_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_ms_nomencladora3_idx` (`ms_2_3a_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_ms_nomencladora4_idx` (`ms_3_2_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_ms_nomencladora5_idx` (`ms_4_2_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_ms_nomencladora6_idx` (`ms_4_3b_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_ms_caso1_idx` (`caso_id_caso` ASC) VISIBLE,
  CONSTRAINT `fk_ms_nomencladora1`
    FOREIGN KEY (`ms_1_3_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ms_nomencladora2`
    FOREIGN KEY (`ms_1_4_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ms_nomencladora3`
    FOREIGN KEY (`ms_2_3a_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ms_nomencladora4`
    FOREIGN KEY (`ms_3_2_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ms_nomencladora5`
    FOREIGN KEY (`ms_4_2_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ms_nomencladora6`
    FOREIGN KEY (`ms_4_3b_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ms_caso1`
    FOREIGN KEY (`caso_id_caso`)
    REFERENCES `smgyd_suimvm`.`caso` (`id_caso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`sdh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`sdh` (
  `id_sdh` INT NOT NULL AUTO_INCREMENT,
  `sdh_1_1` ENUM("Si", "No") NULL,
  `sdh_1_2_id_nomenclador` INT NULL,
  `sdh_1_3` ENUM("Si", "No", "En proceso judicial") NULL,
  `sdh_1_4` ENUM("Trata interna", "Trata internacional") NULL,
  `sdh_1_5_id_nomenclador` INT NULL,
  `sdh_1_6_id_nomenclador` INT NULL,
  `sdh_1_7` ENUM("Si", "No") NULL,
  `sdh_1_8` TEXT NULL,
  `sdh_2_1` ENUM("Si", "No") NULL,
  `sdh_2_3` ENUM("Semanal", "Mensual", "A solicitud de la víctima") NULL,
  `sdh_2_4` ENUM("Menos de 3 meses", "3-6 meses", "6-12 meses", "Más de 1 año") NULL,
  `sdh_3_1` ENUM("Si", "No") NULL,
  `sdh_3_2` ENUM("Menos de 1 dia", "1-7 dias", "Más de una semana", "Más de un mes") NULL,
  `sdh_4_1` ENUM("Si", "No") NULL,
  `sdh_4_2` ENUM("Si", "No") NULL,
  `sdh_4_3` TEXT NULL,
  `sdh_5_1a` ENUM("Si", "No") NULL,
  `sdh_5_1b` TEXT NULL,
  `sdh_5_2a` ENUM("Si", "No") NULL,
  `sdh_5_2b` TEXT NULL,
  `caso_id_caso` INT NOT NULL,
  PRIMARY KEY (`id_sdh`),
  INDEX `fk_sdh_nomencladora1_idx` (`sdh_1_2_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_sdh_nomencladora2_idx` (`sdh_1_5_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_sdh_nomencladora3_idx` (`sdh_1_6_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_sdh_caso1_idx` (`caso_id_caso` ASC) VISIBLE,
  CONSTRAINT `fk_sdh_nomencladora1`
    FOREIGN KEY (`sdh_1_2_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sdh_nomencladora2`
    FOREIGN KEY (`sdh_1_5_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sdh_nomencladora3`
    FOREIGN KEY (`sdh_1_6_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sdh_caso1`
    FOREIGN KEY (`caso_id_caso`)
    REFERENCES `smgyd_suimvm`.`caso` (`id_caso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`dp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`dp` (
  `id_dp` INT NOT NULL AUTO_INCREMENT,
  `dp_1_1` ENUM("Si", "No") NULL,
  `caso_id_caso` INT NOT NULL,
  PRIMARY KEY (`id_dp`),
  INDEX `fk_dp_caso1_idx` (`caso_id_caso` ASC) VISIBLE,
  CONSTRAINT `fk_dp_caso1`
    FOREIGN KEY (`caso_id_caso`)
    REFERENCES `smgyd_suimvm`.`caso` (`id_caso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`jf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`jf` (
  `id_jf` INT NOT NULL AUTO_INCREMENT,
  `caso_id_caso` INT NOT NULL,
  PRIMARY KEY (`id_jf`),
  INDEX `fk_jf_caso1_idx` (`caso_id_caso` ASC) VISIBLE,
  CONSTRAINT `fk_jf_caso1`
    FOREIGN KEY (`caso_id_caso`)
    REFERENCES `smgyd_suimvm`.`caso` (`id_caso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`procuracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`procuracion` (
  `id_procuracion` INT NOT NULL AUTO_INCREMENT,
  `proc_1` ENUM("SI", "NO") NULL,
  `proc_2` ENUM("SI", "NO") NULL,
  `proc_2a` INT NULL,
  `proc_3` ENUM("SI", "NO") NULL,
  `proc_4` ENUM("SI", "NO") NULL,
  `proc_5` ENUM("SI", "NO") NULL,
  `proc_6` VARCHAR(255) NULL,
  `proc_7` DATE NULL,
  `proc_8` DATE NULL,
  `proc_9` ENUM("SI", "NO") NULL,
  `proc_10` INT NULL,
  `proc_11` TEXT NULL,
  `proc_12` ENUM("Violencia familiar", "Divorcios", "Cuidado personal", "Comunicacion", "Cuota alimentaria", "Otro") NULL,
  `proc_13` INT NULL,
  `proc_14` ENUM("SI", "NO", "No Especificado") NULL,
  `proc_15` ENUM("En seguimiento", "Cerrado", "Derivado", "Otro") NULL,
  `proc_16` TEXT NULL,
  PRIMARY KEY (`id_procuracion`),
  INDEX `fk_procuracion_nomencladora1_idx` (`proc_2a` ASC) VISIBLE,
  INDEX `fk_procuracion_nomencladora2_idx` (`proc_10` ASC) VISIBLE,
  INDEX `fk_procuracion_nomencladora3_idx` (`proc_13` ASC) VISIBLE,
  CONSTRAINT `fk_procuracion_nomencladora1`
    FOREIGN KEY (`proc_2a`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_procuracion_nomencladora2`
    FOREIGN KEY (`proc_10`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_procuracion_nomencladora3`
    FOREIGN KEY (`proc_13`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`gob_locales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`gob_locales` (
  `id_gob_locales` INT NOT NULL AUTO_INCREMENT,
  `gobloc_1_1` ENUM("SI", "NO") NULL,
  `gobloc_1_2` ENUM("Denuncia de violencia de género", "Solicitud asistencia económica", "Atención psicológica", "Asesoramiento legal", "Otro") NULL,
  `gobloc_1_3` INT NULL,
  `gobloc_1_4` ENUM("Sec Derechos Humanos", "Centros territoriales de denuncia", "Comisaria de la mujer", "Servicios locales de salud", "Otro") NULL,
  `gobloc_1_5` ENUM("SI", "NO") NULL,
  `gobloc_1_6` ENUM("Refugio seguro", "Asesoria judicial", "Asistencia psicologica especializada") NULL,
  `gobloc_2_1` ENUM("SI", "NO") NULL,
  `gobloc_2_2` ENUM("Bajo", "Medio", "Alto", "Critico") NULL,
  `gobloc_2_3` INT NULL,
  `gobloc_2_4` ENUM("SI", "NO") NULL,
  `gobloc_2_5` ENUM("Policia local", "Juzgado de familia", "Centros de asistencia", "Otro") NULL,
  `gobloc_3_1` ENUM("SI", "NO") NULL,
  `gobloc_3_2` TIME NULL,
  `gobloc_3_3` ENUM("Difusion de búsqueda", "Activación de alerta temprana", "Coordinación con fuerzas de seguridad", "Otro") NULL,
  `gobloc_3_4` ENUM("SI", "NO") NULL,
  `gobloc_4_1` ENUM("SI", "NO") NULL,
  `gobloc_4_2` INT NULL,
  `gobloc_4_3` INT NULL,
  `gobloc_4_4` ENUM("Semanal", "Quincenal", "Mensual", "A solicitud") NULL,
  `gobloc_5_1` ENUM("SI", "NO") NULL,
  `gobloc_5_2` ENUM("Servicios de salud", "Policia local", "Sec Derechos humanos", "Defensoria del Pueblo", "Otro") NULL,
  `gobloc_5_3` ENUM("SI", "NO") NULL,
  `goblocl_5_4` TEXT NULL,
  `gobloc_6_1` ENUM("SI", "NO") NULL,
  `gobloc_6_2a` ENUM("SI", "NO", "Parcialmente") NULL,
  `gobloc_5_6b` TEXT NULL,
  `caso_id_caso` INT NOT NULL,
  PRIMARY KEY (`id_gob_locales`),
  INDEX `fk_gob_locales_nomencladora1_idx` (`gobloc_1_3` ASC) VISIBLE,
  INDEX `fk_gob_locales_nomencladora2_idx` (`gobloc_2_3` ASC) VISIBLE,
  INDEX `fk_gob_locales_nomencladora3_idx` (`gobloc_4_2` ASC) VISIBLE,
  INDEX `fk_gob_locales_nomencladora4_idx` (`gobloc_4_3` ASC) VISIBLE,
  INDEX `fk_gob_locales_caso1_idx` (`caso_id_caso` ASC) VISIBLE,
  CONSTRAINT `fk_gob_locales_nomencladora1`
    FOREIGN KEY (`gobloc_1_3`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gob_locales_nomencladora2`
    FOREIGN KEY (`gobloc_2_3`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gob_locales_nomencladora3`
    FOREIGN KEY (`gobloc_4_2`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gob_locales_nomencladora4`
    FOREIGN KEY (`gobloc_4_3`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gob_locales_caso1`
    FOREIGN KEY (`caso_id_caso`)
    REFERENCES `smgyd_suimvm`.`caso` (`id_caso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`caj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`caj` (
  `id_caj` INT NOT NULL AUTO_INCREMENT,
  `caj_1a` ENUM("SI", "NO") NULL,
  `caj_1b` DATE NULL,
  `caj_1c` INT NULL,
  `caj_1d` INT NULL,
  `caj_2a` ENUM("SI", "NO") NULL,
  `caj_2b` ENUM("SI", "NO") NULL,
  `caj_2c` DATE NULL,
  `caj_2d` ENUM("Activo", "Finalizado") NULL,
  `caj_2e` TEXT NULL,
  `caj_2f` ENUM("No se pudo establecer contacto", "Opto por patrocinio privado", "No quiso presentarse como querellante", "Otro") NULL,
  `caj_3a` ENUM("SI", "NO") NULL,
  `caj_3b` INT NULL,
  `caj_3c` ENUM("SI", "NO") NULL,
  `caj_3d` ENUM("SI", "NO") NULL,
  `caj_3e` DATE NULL,
  `caj_3f` ENUM("Activo", "Finalizado") NULL,
  `caj_3g` TEXT NULL,
  `caj_3h` ENUM("No se pudo establecer contacto", "Opto por patrocinio privado", "No quiso presentarse como querellante", "Otro") NULL,
  `caj_4a` ENUM("SI", "NO") NULL,
  `caj_4b` ENUM("SI", "NO", "Parcialmente") NULL,
  `caj_4c` TEXT NULL,
  `caso_id_caso` INT NOT NULL,
  PRIMARY KEY (`id_caj`),
  INDEX `fk_caj_nomencladora1_idx` (`caj_1c` ASC) VISIBLE,
  INDEX `fk_caj_nomencladora2_idx` (`caj_1d` ASC) VISIBLE,
  INDEX `fk_caj_nomencladora3_idx` (`caj_3b` ASC) VISIBLE,
  INDEX `fk_caj_caso1_idx` (`caso_id_caso` ASC) VISIBLE,
  CONSTRAINT `fk_caj_nomencladora1`
    FOREIGN KEY (`caj_1c`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caj_nomencladora2`
    FOREIGN KEY (`caj_1d`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caj_nomencladora3`
    FOREIGN KEY (`caj_3b`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caj_caso1`
    FOREIGN KEY (`caso_id_caso`)
    REFERENCES `smgyd_suimvm`.`caso` (`id_caso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`sddnayf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`sddnayf` (
  `id_sddnayf` INT NOT NULL AUTO_INCREMENT,
  `sddnayf_6a` ENUM("SI", "NO") NULL,
  `sddnayf_6c` ENUM("SDDNAyF", "Servicios locales de niñez", "Juzgado de familia", "Comisaría", "Escuela", "Servicios de salud", "Organizaciones sociales", "Otro") NULL,
  `sddnayf_7_1` ENUM("SI", "NO") NULL,
  `sddnayf_7_3a` INT NULL,
  `sddnayf_7_3b` ENUM("SDDNAyF", "Servicios locales de niñez", "Escuela", "Servicios de Salud", "Otro") NULL,
  `sddnayf_7_3c` ENUM("Menos de 1 mes", "1-3 meses", "3-6 meses", "Más de 6 meses") NULL,
  `sddnayf_7_3d` ENUM("En curso", "Finalizada") NULL,
  `sddnayf_7_3e` ENUM("Finalizada con seguimiento", "Derivada a otra institución", "Intervención terminada sin seguimiento") NULL,
  `sddnayf_8a` ENUM("Con la víctima", "Con otro familiar", "En institución de protección", "Otro") NULL,
  `sddnayf_8b` ENUM("SI", "NO", "No especificado") NULL,
  `sddnayf_8c` ENUM("SI", "NO") NULL,
  `sddnayf_8d` ENUM("SI", "NO", "En proceso") NULL,
  `sddnayf_8e` ENUM("SI", "NO", "En proceso") NULL,
  `sddnayf_8f` ENUM("SDDNAyF", "Familia extendida", "Organización social", "Otro") NULL,
  `sddnayf_9_1` ENUM("SI", "NO", "En proceso") NULL,
  `sddnayf_9_2` ENUM("SI", "NO") NULL,
  `sddnayf_9_2a` ENUM("Adopción plena", "Adopción simple") NULL,
  `sddnayf_9_2b` DATE NULL,
  `sddnayf_9_2c` ENUM("Juzgado de familia", "SDDNAyF", "Otro") NULL,
  `sddnayf_10_1` ENUM("SI", "NO") NULL,
  `sddnayf_10_2a` INT NULL,
  `sddnayf_10_2b1` ENUM("SI", "NO", "EN PROCESO") NULL,
  `sddnayf_10_2b2` ENUM("SI", "NO", "EN PROCESO") NULL,
  `sddnayf_10_2b3` ENUM("SI", "NO", "EN PROCESO") NULL,
  `sddnayf_10_3a` ENUM("Semanal", "Mensual", "Solo emergencias") NULL,
  `sddnayf_10_3b` ENUM("SDDNAyF", "Servicios locales de niñez", "Servicios de salud", "Escuela", "Organizaciones sociales", "Otro") NULL,
  `caso_id_caso` INT NOT NULL,
  PRIMARY KEY (`id_sddnayf`),
  INDEX `fk_sddnayf_nomencladora1_idx` (`sddnayf_7_3a` ASC) VISIBLE,
  INDEX `fk_sddnayf_nomencladora2_idx` (`sddnayf_10_2a` ASC) VISIBLE,
  INDEX `fk_sddnayf_caso1_idx` (`caso_id_caso` ASC) VISIBLE,
  CONSTRAINT `fk_sddnayf_nomencladora1`
    FOREIGN KEY (`sddnayf_7_3a`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sddnayf_nomencladora2`
    FOREIGN KEY (`sddnayf_10_2a`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sddnayf_caso1`
    FOREIGN KEY (`caso_id_caso`)
    REFERENCES `smgyd_suimvm`.`caso` (`id_caso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`mjys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`mjys` (
  `id_mjys` INT NOT NULL AUTO_INCREMENT,
  `mjys_I_1a` ENUM("Si", "No") NULL,
  `mjys_I_1b` ENUM("Si", "No") NULL,
  `mjys_I_1c` ENUM("Si", "No") NULL,
  `mjys_I_2a_id_nomenclador` INT NULL,
  `mjys_I_2b_id_nomenclador` INT NULL,
  `mjys_I_3a` TIME NULL,
  `mjys_I_3b_id_nomenclador` INT NULL,
  `mjys_I_4a` ENUM("Si", "No") NULL,
  `mjys_I_4b` TIME NULL,
  `mjys_I_5a_id_nomenclador` INT NULL,
  `mjys_I_5b` ENUM("Si", "No") NULL,
  `mjys_I_6a_id_nomenclador` INT NULL,
  `mjys_I_6b` ENUM("Si", "No") NULL,
  `mjys_I_7a` ENUM("No", "La propia víctima", "Vecinos", "Familiares") NULL,
  `mjys_I_7b` ENUM("Si", "No") NULL,
  `mjys_I_8a` ENUM("Si", "No") NULL,
  `mjys_I_9a1` INT NULL,
  `mjys_I_9a2` ENUM("Si", "No") NULL,
  `mjys_I_9b1_id_nomenclador` INT NULL,
  `mjys_I_9b2` ENUM("Si", "No") NULL,
  `mjys_II_a1a` INT NULL,
  `mjys_II_a1b_id_nomenclador` INT NULL,
  `mjys_II_a1c` DATE NULL,
  `mjys_II_a1d_id_nomenclador` INT NULL,
  `mjys_II_a2a` ENUM("Si", "No") NULL,
  `mjys_II_a2b_id_nomenclador` INT NULL,
  `mjys_II_a2c` ENUM("Si", "No") NULL,
  `mjys_II_a3a` ENUM("Si", "No") NULL,
  `mjys_II_a3b_id_nomenclador` INT NULL,
  `mjys_II_a3c` ENUM("Cumplidas", "No cumplidas", "En evaluación") NULL,
  `mjys_II_a4a` ENUM("Si", "No") NULL,
  `mjys_II_b1a` ENUM("Si", "No") NULL,
  `mjys_II_b1b1_id_nomenclador` INT NULL,
  `mjys_II_b1b2` DATE NULL,
  `mjys_II_b1b3_id_nomenclador` INT NULL,
  `mjys_II_b1c` ENUM("Si", "No") NULL,
  `mjys_II_b2a` ENUM("Si", "No") NULL,
  `mjys_II_b2b1_id_nomenclador` INT NULL,
  `mjys_II_b2b2` DATE NULL,
  `mjys_II_b2b3_id_nomenclador` INT NULL,
  `mjys_II_c1a` ENUM("Si", "No") NULL,
  `mjys_II_c1b1_id_nomenclador` INT NULL,
  `mjys_II_c1b2` DATE NULL,
  `mjys_II_c1b3_id_nomenclador` INT NULL,
  `mjys_II_c2a` ENUM("Si", "No") NULL,
  `mjys_II_c2b` INT NULL,
  `mjys_III_1a` ENUM("Si", "No") NULL,
  `mjys_III_5a` ENUM("Si", "No") NULL,
  `mjys_III_5b1_id_nomenclador` INT NULL,
  `mjys_III_5b3_id_nomenclador` INT NULL,
  `mjys_III_6a` ENUM("Si", "No") NULL,
  `mjys_III_6b` ENUM("Si", "No") NULL,
  `mjys_III_6b1` TEXT NULL,
  `mjys_IV_1a` ENUM("Si", "No") NULL,
  `mjys_IV_1b` DATE NULL,
  `mjys_IV_1c_id_nomenclador` INT NULL,
  `mjys_IV_1d` ENUM("Si", "No") NULL,
  `mjys_IV_1e` ENUM("Si", "No", "No se sabe") NULL,
  `mjys_IV_1g` ENUM("Si", "No") NULL,
  `mjys_IV_2a` ENUM("Si", "No") NULL,
  `mjys_IV_2c_id_nomenclador` INT NULL,
  `mjys_IV_2e_id_nomenclador` INT NULL,
  `mjys_IV_3a` VARCHAR(45) NULL,
  `mjys_IV_3b` VARCHAR(155) NULL,
  `mjys_IV_3c` ENUM("Personal del programa", "Psicólogos", "Abogados") NULL,
  `mjys_IV_3d_id_nomenclador` INT NULL,
  `mjys_IV_4a` ENUM("Si", "No", "No se sabe") NULL,
  `mjys_IV_4b` ENUM("Falta de recursos", "Dificultad de acceso a la víctima", "Falta de aceptación de la protección") NULL,
  `mjys_IV_4c` ENUM("Si", "No") NULL,
  `mjys_V_1a` ENUM("Si", "No") NULL,
  `mjys_V_1b_id_nomenclador` INT NULL,
  `mjys_V_1c` DATE NULL,
  `mjys_V_2a` ENUM("Si", "No") NULL,
  `mjys_V_2c` ENUM("Actividades ilegales del agresor", "Vínculo con bandas criminales", "Distribución o venta de drogas") NULL,
  `mjys_V_3d4` INT NULL,
  `mjys_V_3d5` TEXT NULL,
  `mjys_V_3d6` TEXT NULL,
  `mjys_V_3e` ENUM("Si", "No") NULL,
  `mjys_V_4a` ENUM("Si", "No") NULL,
  `mjys_V_4b_id_nomenclador` INT NULL,
  `mjys_V_5a` ENUM("Si", "No") NULL,
  `mjys_V_5b` ENUM("Bajo", "Moderado", "Alto") NULL,
  `mjys_V_5d` ENUM("Semanal", "Mensual", "Al cierre de cada accion") NULL,
  `mjys_VI_1a` ENUM("Si", "No") NULL,
  `mjys_VI_1b_id_nomenclador` INT NULL,
  `mjys_VI_1c` INT NULL,
  `mjys_VI_1d` DATE NULL,
  `mjys_VI_1e` ENUM("Si", "No") NULL,
  `mjys_VI_1f_id_nomenclador` INT NULL,
  `mjys_VI_1g` ENUM("Completo", "Parcial", "No cumplido", "Desconocido") NULL,
  `mjys_VI_1h_id_nomenclador` INT NULL,
  `mjys_VI_2a` ENUM("Si", "No") NULL,
  `mjys_VI_2b_id_nomenclador` INT NULL,
  `mjys_VI_2c` INT NULL,
  `mjys_VI_2d` DATE NULL,
  `mjys_VI_2e` ENUM("Si", "No") NULL,
  `mjys_VI_3a` ENUM("Si", "No") NULL,
  `mjys_VI_3b1_id_nomenclador` INT NULL,
  `mjys_VI_3b2_id_nomenclador` INT NULL,
  `mjys_VI_3b3_id_nomenclador` INT NULL,
  `mjys_VI_3b4` ENUM("Completo", "En curso", "Incompleto") NULL,
  `mjys_VI_3c1_id_nomenclador` INT NULL,
  `mjys_VI_3c2_id_nomenclador` INT NULL,
  `mjys_VI_3c3` TEXT NULL,
  `mjys_VI_4a` ENUM("Si", "No") NULL,
  `mjys_VI_4b` ENUM("Bajo", "Moderado", "Alto") NULL,
  `mjys_VI_4c` TEXT NULL,
  `caso_id_caso` INT NOT NULL,
  PRIMARY KEY (`id_mjys`),
  INDEX `fk_mjys_nomencladora1_idx` (`mjys_I_2a_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora2_idx` (`mjys_I_2b_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora3_idx` (`mjys_I_3b_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora4_idx` (`mjys_I_5a_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora5_idx` (`mjys_I_6a_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora6_idx` (`mjys_I_9b1_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora7_idx` (`mjys_II_a1d_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora8_idx` (`mjys_II_a2b_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora9_idx` (`mjys_II_a3b_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora10_idx` (`mjys_II_b1b1_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora11_idx` (`mjys_II_b1b3_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora12_idx` (`mjys_II_b2b1_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora13_idx` (`mjys_II_b2b3_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora14_idx` (`mjys_II_c1b1_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora15_idx` (`mjys_II_c1b3_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora16_idx` (`mjys_III_5b1_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora17_idx` (`mjys_III_5b3_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora18_idx` (`mjys_IV_1c_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora19_idx` (`mjys_IV_2c_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora20_idx` (`mjys_IV_2e_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora21_idx` (`mjys_IV_3d_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora22_idx` (`mjys_V_1b_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora23_idx` (`mjys_V_4b_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora24_idx` (`mjys_V_5b` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora25_idx` (`mjys_VI_1b_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora26_idx` (`mjys_VI_1f_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora27_idx` (`mjys_VI_1h_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora28_idx` (`mjys_VI_2b_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora29_idx` (`mjys_VI_3b1_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora30_idx` (`mjys_VI_3b2_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora31_idx` (`mjys_VI_3b3_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora32_idx` (`mjys_VI_3c1_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora33_idx` (`mjys_VI_3c2_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_nomencladora34_idx` (`mjys_II_a1b_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_mjys_caso1_idx` (`caso_id_caso` ASC) VISIBLE,
  CONSTRAINT `fk_mjys_nomencladora1`
    FOREIGN KEY (`mjys_I_2a_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora2`
    FOREIGN KEY (`mjys_I_2b_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora3`
    FOREIGN KEY (`mjys_I_3b_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora4`
    FOREIGN KEY (`mjys_I_5a_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora5`
    FOREIGN KEY (`mjys_I_6a_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora6`
    FOREIGN KEY (`mjys_I_9b1_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora7`
    FOREIGN KEY (`mjys_II_a1d_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora8`
    FOREIGN KEY (`mjys_II_a2b_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora9`
    FOREIGN KEY (`mjys_II_a3b_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora10`
    FOREIGN KEY (`mjys_II_b1b1_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora11`
    FOREIGN KEY (`mjys_II_b1b3_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora12`
    FOREIGN KEY (`mjys_II_b2b1_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora13`
    FOREIGN KEY (`mjys_II_b2b3_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora14`
    FOREIGN KEY (`mjys_II_c1b1_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora15`
    FOREIGN KEY (`mjys_II_c1b3_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora16`
    FOREIGN KEY (`mjys_III_5b1_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora17`
    FOREIGN KEY (`mjys_III_5b3_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora18`
    FOREIGN KEY (`mjys_IV_1c_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora19`
    FOREIGN KEY (`mjys_IV_2c_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora20`
    FOREIGN KEY (`mjys_IV_2e_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora21`
    FOREIGN KEY (`mjys_IV_3d_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora22`
    FOREIGN KEY (`mjys_V_1b_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora23`
    FOREIGN KEY (`mjys_V_4b_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora24`
    FOREIGN KEY (`mjys_V_5b`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora25`
    FOREIGN KEY (`mjys_VI_1b_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora26`
    FOREIGN KEY (`mjys_VI_1f_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora27`
    FOREIGN KEY (`mjys_VI_1h_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora28`
    FOREIGN KEY (`mjys_VI_2b_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora29`
    FOREIGN KEY (`mjys_VI_3b1_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora30`
    FOREIGN KEY (`mjys_VI_3b2_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora31`
    FOREIGN KEY (`mjys_VI_3b3_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora32`
    FOREIGN KEY (`mjys_VI_3c1_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora33`
    FOREIGN KEY (`mjys_VI_3c2_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_nomencladora34`
    FOREIGN KEY (`mjys_II_a1b_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjys_caso1`
    FOREIGN KEY (`caso_id_caso`)
    REFERENCES `smgyd_suimvm`.`caso` (`id_caso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`delito_denunciado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`delito_denunciado` (
  `id_delito_denunciado` INT NOT NULL AUTO_INCREMENT,
  `mjys_id_mjys` INT NOT NULL,
  `mjys_II_a1b_id_nomenclador` INT NOT NULL,
  INDEX `fk_delito_denunciado_mjys1_idx` (`mjys_id_mjys` ASC) VISIBLE,
  PRIMARY KEY (`id_delito_denunciado`),
  INDEX `fk_delito_denunciado_nomencladora1_idx` (`mjys_II_a1b_id_nomenclador` ASC) VISIBLE,
  CONSTRAINT `fk_delito_denunciado_mjys1`
    FOREIGN KEY (`mjys_id_mjys`)
    REFERENCES `smgyd_suimvm`.`mjys` (`id_mjys`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_delito_denunciado_nomencladora1`
    FOREIGN KEY (`mjys_II_a1b_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`violencia_denunciada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`violencia_denunciada` (
  `id_violencia_denunciada` INT NOT NULL AUTO_INCREMENT,
  `mjys_id_mjys` INT NOT NULL,
  `mjys_II_a1e_id_nomenclador` INT NOT NULL,
  PRIMARY KEY (`id_violencia_denunciada`),
  INDEX `fk_violencia_denunciada_mjys1_idx` (`mjys_id_mjys` ASC) VISIBLE,
  INDEX `fk_violencia_denunciada_nomencladora1_idx` (`mjys_II_a1e_id_nomenclador` ASC) VISIBLE,
  CONSTRAINT `fk_violencia_denunciada_mjys1`
    FOREIGN KEY (`mjys_id_mjys`)
    REFERENCES `smgyd_suimvm`.`mjys` (`id_mjys`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_violencia_denunciada_nomencladora1`
    FOREIGN KEY (`mjys_II_a1e_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`quien_denuncia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`quien_denuncia` (
  `id_quien_denuncia` INT NOT NULL AUTO_INCREMENT,
  `mjys_id_mjys` INT NOT NULL,
  `mjys_III_1b_id_nomenclador` INT NOT NULL,
  PRIMARY KEY (`id_quien_denuncia`),
  INDEX `fk_quien_denuncia_mjys1_idx` (`mjys_id_mjys` ASC) VISIBLE,
  INDEX `fk_quien_denuncia_nomencladora1_idx` (`mjys_III_1b_id_nomenclador` ASC) VISIBLE,
  CONSTRAINT `fk_quien_denuncia_mjys1`
    FOREIGN KEY (`mjys_id_mjys`)
    REFERENCES `smgyd_suimvm`.`mjys` (`id_mjys`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quien_denuncia_nomencladora1`
    FOREIGN KEY (`mjys_III_1b_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`motivos_denuncia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`motivos_denuncia` (
  `id_motivo_denuncia` INT NOT NULL AUTO_INCREMENT,
  `mjys_id_mjys` INT NOT NULL,
  `mjys_III_2a_id_nomenclador` INT NOT NULL,
  `mjys_III_3a` DATE NULL,
  `mjys_III_3b` TEXT NULL,
  `mjys_III_3c` ENUM("Domicilio", "Lugar de trabajo", "Espacio público", "Redes sociales o medios digitales") NULL,
  `mjys_III_3d_id_nomenclador` INT NOT NULL,
  `mjys_III_4a` ENUM("Si", "No") NULL,
  `mjys_III_4c_id_nomenclador` INT NULL,
  PRIMARY KEY (`id_motivo_denuncia`),
  INDEX `fk_motivo_denuncia_mjys1_idx` (`mjys_id_mjys` ASC) VISIBLE,
  INDEX `fk_motivo_denuncia_nomencladora1_idx` (`mjys_III_2a_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_motivos_denuncia_nomencladora1_idx` (`mjys_III_3d_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_motivos_denuncia_nomencladora2_idx` (`mjys_III_4c_id_nomenclador` ASC) VISIBLE,
  CONSTRAINT `fk_motivo_denuncia_mjys1`
    FOREIGN KEY (`mjys_id_mjys`)
    REFERENCES `smgyd_suimvm`.`mjys` (`id_mjys`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_motivo_denuncia_nomencladora1`
    FOREIGN KEY (`mjys_III_2a_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_motivos_denuncia_nomencladora1`
    FOREIGN KEY (`mjys_III_3d_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_motivos_denuncia_nomencladora2`
    FOREIGN KEY (`mjys_III_4c_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`medida_motivos_denuncia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`medida_motivos_denuncia` (
  `id_medida_motivos_denuncia` INT NOT NULL AUTO_INCREMENT,
  `motivos_denuncia_id_motivo_denuncia` INT NOT NULL,
  `mjys_III_4b_id_nomenclador` INT NOT NULL,
  PRIMARY KEY (`id_medida_motivos_denuncia`),
  INDEX `fk_medida_motivos_denuncia_motivos_denuncia1_idx` (`motivos_denuncia_id_motivo_denuncia` ASC) VISIBLE,
  INDEX `fk_medida_motivos_denuncia_nomencladora1_idx` (`mjys_III_4b_id_nomenclador` ASC) VISIBLE,
  CONSTRAINT `fk_medida_motivos_denuncia_motivos_denuncia1`
    FOREIGN KEY (`motivos_denuncia_id_motivo_denuncia`)
    REFERENCES `smgyd_suimvm`.`motivos_denuncia` (`id_motivo_denuncia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medida_motivos_denuncia_nomencladora1`
    FOREIGN KEY (`mjys_III_4b_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`motivos_denuncia_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`motivos_denuncia_funcionario` (
  `id_motivos_denuncia_funcionario` INT NOT NULL AUTO_INCREMENT,
  `mjys_id_mjys` INT NOT NULL,
  `mjys_III_5b2_id_nomenclador` INT NOT NULL,
  PRIMARY KEY (`id_motivos_denuncia_funcionario`),
  INDEX `fk_motivos_denuncia_funcionario_mjys1_idx` (`mjys_id_mjys` ASC) VISIBLE,
  INDEX `fk_motivos_denuncia_funcionario_nomencladora1_idx` (`mjys_III_5b2_id_nomenclador` ASC) VISIBLE,
  CONSTRAINT `fk_motivos_denuncia_funcionario_mjys1`
    FOREIGN KEY (`mjys_id_mjys`)
    REFERENCES `smgyd_suimvm`.`mjys` (`id_mjys`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_motivos_denuncia_funcionario_nomencladora1`
    FOREIGN KEY (`mjys_III_5b2_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`medidas_proteccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`medidas_proteccion` (
  `id_medidas_proteccion` INT NOT NULL AUTO_INCREMENT,
  `mjys_id_mjys` INT NOT NULL,
  `codigo_pregunta` VARCHAR(45) NOT NULL,
  `mjys_IV_1f_id_nomenclador` INT NULL,
  `mjys_IV_2d_id_nomenclador` INT NULL,
  `mjys_V_5c_id_nomenclador` INT NULL,
  PRIMARY KEY (`id_medidas_proteccion`),
  INDEX `fk_medidas_proteccion_mjys1_idx` (`mjys_id_mjys` ASC) VISIBLE,
  INDEX `fk_medidas_proteccion_nomencladora1_idx` (`mjys_IV_1f_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_medidas_proteccion_nomencladora2_idx` (`mjys_IV_2d_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_medidas_proteccion_nomencladora3_idx` (`mjys_V_5c_id_nomenclador` ASC) VISIBLE,
  CONSTRAINT `fk_medidas_proteccion_mjys1`
    FOREIGN KEY (`mjys_id_mjys`)
    REFERENCES `smgyd_suimvm`.`mjys` (`id_mjys`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medidas_proteccion_nomencladora1`
    FOREIGN KEY (`mjys_IV_1f_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medidas_proteccion_nomencladora2`
    FOREIGN KEY (`mjys_IV_2d_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medidas_proteccion_nomencladora3`
    FOREIGN KEY (`mjys_V_5c_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`persona_protegida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`persona_protegida` (
  `id_persona_protegida` INT NOT NULL AUTO_INCREMENT,
  `mjys_id_mjys` INT NOT NULL,
  `mjys_IV_2b_id_nomenclador` INT NOT NULL,
  PRIMARY KEY (`id_persona_protegida`),
  INDEX `fk_persona_protegida_mjys1_idx` (`mjys_id_mjys` ASC) VISIBLE,
  INDEX `fk_persona_protegida_nomencladora1_idx` (`mjys_IV_2b_id_nomenclador` ASC) VISIBLE,
  CONSTRAINT `fk_persona_protegida_mjys1`
    FOREIGN KEY (`mjys_id_mjys`)
    REFERENCES `smgyd_suimvm`.`mjys` (`id_mjys`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_protegida_nomencladora1`
    FOREIGN KEY (`mjys_IV_2b_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`acciones_aic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`acciones_aic` (
  `id_acciones_aic` INT NOT NULL AUTO_INCREMENT,
  `mjys_id_mjys` INT NOT NULL,
  `mjys_V_1d_id_nomenclador` INT NOT NULL,
  PRIMARY KEY (`id_acciones_aic`),
  INDEX `fk_acciones_aic_mjys1_idx` (`mjys_id_mjys` ASC) VISIBLE,
  INDEX `fk_acciones_aic_nomencladora1_idx` (`mjys_V_1d_id_nomenclador` ASC) VISIBLE,
  CONSTRAINT `fk_acciones_aic_mjys1`
    FOREIGN KEY (`mjys_id_mjys`)
    REFERENCES `smgyd_suimvm`.`mjys` (`id_mjys`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acciones_aic_nomencladora1`
    FOREIGN KEY (`mjys_V_1d_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`colaboracion_agencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`colaboracion_agencia` (
  `id_colaboracion_agencia` INT NOT NULL AUTO_INCREMENT,
  `mjys_id_mjys` INT NOT NULL,
  `mjys_V_4c_id_nomenclador` INT NOT NULL,
  PRIMARY KEY (`id_colaboracion_agencia`),
  INDEX `fk_colaboracion_agencia_mjys1_idx` (`mjys_id_mjys` ASC) VISIBLE,
  INDEX `fk_colaboracion_agencia_nomencladora1_idx` (`mjys_V_4c_id_nomenclador` ASC) VISIBLE,
  CONSTRAINT `fk_colaboracion_agencia_mjys1`
    FOREIGN KEY (`mjys_id_mjys`)
    REFERENCES `smgyd_suimvm`.`mjys` (`id_mjys`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_colaboracion_agencia_nomencladora1`
    FOREIGN KEY (`mjys_V_4c_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`diagnostico_asociado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`diagnostico_asociado` (
  `id_diagnostico_asociado` INT NOT NULL AUTO_INCREMENT,
  `ms_id_ms` INT NOT NULL,
  `ms_2_1_id_nomenclador` INT NOT NULL,
  PRIMARY KEY (`id_diagnostico_asociado`),
  INDEX `fk_diagnostico_asociado_ms1_idx` (`ms_id_ms` ASC) VISIBLE,
  INDEX `fk_diagnostico_asociado_nomencladora1_idx` (`ms_2_1_id_nomenclador` ASC) VISIBLE,
  CONSTRAINT `fk_diagnostico_asociado_ms1`
    FOREIGN KEY (`ms_id_ms`)
    REFERENCES `smgyd_suimvm`.`ms` (`id_ms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diagnostico_asociado_nomencladora1`
    FOREIGN KEY (`ms_2_1_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`ruta_atencion_instituciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`ruta_atencion_instituciones` (
  `id_ruta_atencion_instituciones` INT NOT NULL AUTO_INCREMENT,
  `ms_id_ms` INT NOT NULL,
  `ms_3_3` TEXT NULL,
  PRIMARY KEY (`id_ruta_atencion_instituciones`),
  INDEX `fk_ruta_atencion_instituciones_ms1_idx` (`ms_id_ms` ASC) VISIBLE,
  CONSTRAINT `fk_ruta_atencion_instituciones_ms1`
    FOREIGN KEY (`ms_id_ms`)
    REFERENCES `smgyd_suimvm`.`ms` (`id_ms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`proteccion_ofrecida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`proteccion_ofrecida` (
  `id_proteccion_ofrecida` INT NOT NULL AUTO_INCREMENT,
  `sdh_id_sdh` INT NOT NULL,
  `sdh_2_2_id_nomenclador` INT NOT NULL,
  PRIMARY KEY (`id_proteccion_ofrecida`),
  INDEX `fk_proteccion_ofrecida_sdh1_idx` (`sdh_id_sdh` ASC) VISIBLE,
  INDEX `fk_proteccion_ofrecida_nomencladora1_idx` (`sdh_2_2_id_nomenclador` ASC) VISIBLE,
  CONSTRAINT `fk_proteccion_ofrecida_sdh1`
    FOREIGN KEY (`sdh_id_sdh`)
    REFERENCES `smgyd_suimvm`.`sdh` (`id_sdh`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proteccion_ofrecida_nomencladora1`
    FOREIGN KEY (`sdh_2_2_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`solicitud_asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`solicitud_asistencia` (
  `id_solicitud_asistencia` INT NOT NULL AUTO_INCREMENT,
  `dp_id_dp` INT NOT NULL,
  `dp_1_2` DATE NULL,
  `dp_1_3_id_nomenclador` INT NULL,
  `dp_1_4_id_nomenclador` INT NULL,
  `dp_1_5` ENUM("Plan de seguridad personalizado", "Gestión de medidas cautelares", "Seguimiento periódico") NULL,
  `dp_1_6` ENUM("Si", "No") NULL,
  `dp_1_7` TEXT NULL,
  `dp_1_8` ENUM("Atención especializada", "Refugio", "Asistencia económica") NULL,
  `dp_2_1` ENUM("Si", "No") NULL,
  `dp_2_2` DATE NULL,
  `dp_2_3` ENUM("Bajo", "Medio", "Alto", "Critico") NULL,
  `dp_2_4_id_nomenclador` INT NULL,
  `dp_2_5` ENUM("Si", "No") NULL,
  `dp_2_6` ENUM("Falta de recursos", "Negativa de la victima", "Demora judicial") NULL,
  `dp_3_1` ENUM("Si", "No") NULL,
  `dp_3_2` ENUM("Semanal", "Quincenal", "Mensual") NULL,
  `dp_3_3` ENUM("Telefonico", "Presencial", "Correo electronico") NULL,
  `dp_3_4` ENUM("Si", "No") NULL,
  `dp_3_5` TEXT NULL,
  `dp_4_1` ENUM("Si", "No") NULL,
  `dp_4_2_id_nomenclador` INT NULL,
  `dp_4_1` ENUM("Si", "No") NULL,
  `dp_4_2_id_nomenclador` INT NULL,
  `dp_4_3_id_nomenclador` INT NULL,
  `dp_4_4` ENUM("Si", "No") NULL,
  `dp_4_5` ENUM("Si", "No") NULL,
  `dp_5_1` ENUM("Si", "No") NULL,
  `dp_5_2` ENUM("Policia", "Poder judicial", "Servicios de salud", "Organizaciones sociales") NULL,
  `dp_5_3` ENUM("Intercambio de información", "Planificación conjunta de medidas", "Derivaciones") NULL,
  `dp_5_4` ENUM("Si", "No") NULL,
  `dp_5_5` TEXT NULL,
  `dp_6_1` ENUM("Si", "No") NULL,
  `dp_6_2` TEXT NULL,
  `dp_6_3` TEXT NULL,
  PRIMARY KEY (`id_solicitud_asistencia`),
  INDEX `fk_solicitud_asistencia_dp1_idx` (`dp_id_dp` ASC) VISIBLE,
  INDEX `fk_solicitud_asistencia_nomencladora1_idx` (`dp_1_3_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_solicitud_asistencia_nomencladora2_idx` (`dp_1_4_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_solicitud_asistencia_nomencladora3_idx` (`dp_2_4_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_solicitud_asistencia_nomencladora4_idx` (`dp_4_2_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_solicitud_asistencia_nomencladora5_idx` (`dp_4_2_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_solicitud_asistencia_nomencladora6_idx` (`dp_4_3_id_nomenclador` ASC) VISIBLE,
  CONSTRAINT `fk_solicitud_asistencia_dp1`
    FOREIGN KEY (`dp_id_dp`)
    REFERENCES `smgyd_suimvm`.`dp` (`id_dp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_asistencia_nomencladora1`
    FOREIGN KEY (`dp_1_3_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_asistencia_nomencladora2`
    FOREIGN KEY (`dp_1_4_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_asistencia_nomencladora3`
    FOREIGN KEY (`dp_2_4_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_asistencia_nomencladora4`
    FOREIGN KEY (`dp_4_2_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_asistencia_nomencladora5`
    FOREIGN KEY (`dp_4_2_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_asistencia_nomencladora6`
    FOREIGN KEY (`dp_4_3_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`jf_denuncias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`jf_denuncias` (
  `id_jf_denuncias` INT NOT NULL AUTO_INCREMENT,
  `jf_id_jf` INT NOT NULL,
  `jf_1_1` ENUM("Si", "No") NULL,
  PRIMARY KEY (`id_jf_denuncias`),
  INDEX `fk_jf_denuncias_jf1_idx` (`jf_id_jf` ASC) VISIBLE,
  CONSTRAINT `fk_jf_denuncias_jf1`
    FOREIGN KEY (`jf_id_jf`)
    REFERENCES `smgyd_suimvm`.`jf` (`id_jf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`causa_federal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`causa_federal` (
  `id_causa_federal` INT NOT NULL AUTO_INCREMENT,
  `jf_denuncias_id_jf_denuncias` INT NOT NULL,
  `jf_1_2_id_nomenclador` INT NULL,
  `jf_1_3a` ENUM("Víctima de trata", "Víctima de violencia en contexto de criminalidad organizada") NULL,
  `jf_1_3b` ENUM("Principal", "Secundario", "Participante incidental") NULL,
  `jf_1_3c` ENUM("Colaboradora") NULL,
  `jf_2_1` ENUM("Si", "No", "No especificado") NULL,
  `jf_2_2` ENUM("Distribución", "Producción", "Transporte", "Venta", "Colaboración logística") NULL,
  `jf_2_3_id_nomenclador` INT NULL,
  `jf_3_1` ENUM("Si", "No") NULL,
  `jf_3_2` ENUM("Explotación sexual", "Explotación laboral", "Servidumbre") NULL,
  `jf_3_3` ENUM("Si", "No") NULL,
  `jf_3_4` TEXT NULL,
  `jf_4_1` ENUM("Si", "No") NULL,
  `jf_4_3` ENUM("Si", "No", "No especificado") NULL,
  `jf_5_1_id_nomenclador` INT NULL,
  `jf_5_2a` ENUM("Si", "No") NULL,
  `jf_5_2b` ENUM("Si", "No") NULL,
  `jf_6_1` ENUM("Si", "No") NULL,
  `jf_6_2_id_nomenclador` INT NULL,
  `jf_6_3` ENUM("Si", "No") NULL,
  PRIMARY KEY (`id_causa_federal`),
  INDEX `fk_causa_federal_jf_denuncias1_idx` (`jf_denuncias_id_jf_denuncias` ASC) VISIBLE,
  INDEX `fk_causa_federal_nomencladora1_idx` (`jf_1_2_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_causa_federal_nomencladora2_idx` (`jf_2_3_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_causa_federal_nomencladora3_idx` (`jf_5_1_id_nomenclador` ASC) VISIBLE,
  INDEX `fk_causa_federal_nomencladora4_idx` (`jf_6_2_id_nomenclador` ASC) VISIBLE,
  CONSTRAINT `fk_causa_federal_jf_denuncias1`
    FOREIGN KEY (`jf_denuncias_id_jf_denuncias`)
    REFERENCES `smgyd_suimvm`.`jf_denuncias` (`id_jf_denuncias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_causa_federal_nomencladora1`
    FOREIGN KEY (`jf_1_2_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_causa_federal_nomencladora2`
    FOREIGN KEY (`jf_2_3_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_causa_federal_nomencladora3`
    FOREIGN KEY (`jf_5_1_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_causa_federal_nomencladora4`
    FOREIGN KEY (`jf_6_2_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`contexto_criminalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`contexto_criminalidad` (
  `id_contexto_criminalidad` INT NOT NULL AUTO_INCREMENT,
  `causa_federal_id_causa_federal` INT NOT NULL,
  `nomencladora_id_nomenclador` INT NOT NULL,
  PRIMARY KEY (`id_contexto_criminalidad`),
  INDEX `fk_contexto_criminalidad_causa_federal1_idx` (`causa_federal_id_causa_federal` ASC) VISIBLE,
  INDEX `fk_contexto_criminalidad_nomencladora1_idx` (`nomencladora_id_nomenclador` ASC) VISIBLE,
  CONSTRAINT `fk_contexto_criminalidad_causa_federal1`
    FOREIGN KEY (`causa_federal_id_causa_federal`)
    REFERENCES `smgyd_suimvm`.`causa_federal` (`id_causa_federal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contexto_criminalidad_nomencladora1`
    FOREIGN KEY (`nomencladora_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`procuracion_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`procuracion_copy1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`intervencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`intervencion` (
  `id_intervencion` INT NOT NULL AUTO_INCREMENT,
  `sddnayf_id_sddnayf` INT NOT NULL,
  `sddnayf_1a` ENUM("VICTIMA", "AGRESOR") NOT NULL,
  `sddnayf_2a` INT NULL,
  `sddnayf_2b` ENUM("Alojamiento en hogar de transito", "Integración en familia solidaria", "Internacion en centro especializado") NULL,
  `sddnayf_2c` TEXT NULL,
  `sddnayf_3_1a` ENUM("SI", "NO") NULL,
  `sddnayf_3_1b` DATE NULL,
  `sddnayf_3_1c` ENUM("Violencia doméstica", "Situación de vulnerabilidad social, abuso o negligencia", "Otro") NULL,
  `sddnayf_3_1d` ENUM("SDDNAyF", "Servicios locales de niñez", "Otro") NULL,
  `sddnayf_3_2a` ENUM("SI", "NO") NULL,
  `sddnayf_3_2b` ENUM("Conflicto con la Ley Penal", "Delito menor", "Delito grave") NULL,
  `sddnayf_3_2c` ENUM("Intervención inmediata", "Seguimiento posterior", "Programa de reinserción") NULL,
  PRIMARY KEY (`id_intervencion`),
  INDEX `fk_intervencion_sddnayf1_idx` (`sddnayf_id_sddnayf` ASC) VISIBLE,
  INDEX `fk_intervencion_nomencladora1_idx` (`sddnayf_2a` ASC) VISIBLE,
  CONSTRAINT `fk_intervencion_sddnayf1`
    FOREIGN KEY (`sddnayf_id_sddnayf`)
    REFERENCES `smgyd_suimvm`.`sddnayf` (`id_sddnayf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_intervencion_nomencladora1`
    FOREIGN KEY (`sddnayf_2a`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`programas_recibidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`programas_recibidos` (
  `id_programas_recibidos` INT NOT NULL AUTO_INCREMENT,
  `programa` VARCHAR(45) NULL,
  PRIMARY KEY (`id_programas_recibidos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`programas_recibidos_has_intervencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`programas_recibidos_has_intervencion` (
  `programas_recibidos_id_programas_recibidos` INT NOT NULL,
  `intervencion_id_intervencion` INT NOT NULL,
  PRIMARY KEY (`programas_recibidos_id_programas_recibidos`, `intervencion_id_intervencion`),
  INDEX `fk_programas_recibidos_has_intervencion_intervencion1_idx` (`intervencion_id_intervencion` ASC) VISIBLE,
  INDEX `fk_programas_recibidos_has_intervencion_programas_recibidos_idx` (`programas_recibidos_id_programas_recibidos` ASC) VISIBLE,
  CONSTRAINT `fk_programas_recibidos_has_intervencion_programas_recibidos1`
    FOREIGN KEY (`programas_recibidos_id_programas_recibidos`)
    REFERENCES `smgyd_suimvm`.`programas_recibidos` (`id_programas_recibidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_programas_recibidos_has_intervencion_intervencion1`
    FOREIGN KEY (`intervencion_id_intervencion`)
    REFERENCES `smgyd_suimvm`.`intervencion` (`id_intervencion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`ninios_vinculados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`ninios_vinculados` (
  `id_vinculado` INT NOT NULL AUTO_INCREMENT,
  `sddnayf_5a` VARCHAR(55) NULL,
  `sddnayf_5b` DATE NULL,
  `sddnayf_5c` INT NULL,
  `sddnayf_5d` VARCHAR(8) NULL,
  `sddnayf_5e` ENUM("Hija/o biológica/o", "Hijastra/o", "Otro") NULL,
  `sddnayf_id_sddnayf` INT NOT NULL,
  PRIMARY KEY (`id_vinculado`),
  INDEX `fk_ninios_vinculados_sddnayf1_idx` (`sddnayf_id_sddnayf` ASC) VISIBLE,
  CONSTRAINT `fk_ninios_vinculados_sddnayf1`
    FOREIGN KEY (`sddnayf_id_sddnayf`)
    REFERENCES `smgyd_suimvm`.`sddnayf` (`id_sddnayf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`tipo_vulneracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`tipo_vulneracion` (
  `id_tipo_vulneracion` INT NOT NULL AUTO_INCREMENT,
  `vulneracion` VARCHAR(55) NULL,
  PRIMARY KEY (`id_tipo_vulneracion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`tipo_vulneracion_has_sddnayf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`tipo_vulneracion_has_sddnayf` (
  `tipo_vulneracion_id_tipo_vulneracion` INT NOT NULL,
  `sddnayf_id_sddnayf` INT NOT NULL,
  `sddnayf_6b` VARCHAR(45) NULL,
  PRIMARY KEY (`tipo_vulneracion_id_tipo_vulneracion`, `sddnayf_id_sddnayf`),
  INDEX `fk_tipo_vulneracion_has_sddnayf_sddnayf1_idx` (`sddnayf_id_sddnayf` ASC) VISIBLE,
  INDEX `fk_tipo_vulneracion_has_sddnayf_tipo_vulneracion1_idx` (`tipo_vulneracion_id_tipo_vulneracion` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_vulneracion_has_sddnayf_tipo_vulneracion1`
    FOREIGN KEY (`tipo_vulneracion_id_tipo_vulneracion`)
    REFERENCES `smgyd_suimvm`.`tipo_vulneracion` (`id_tipo_vulneracion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_vulneracion_has_sddnayf_sddnayf1`
    FOREIGN KEY (`sddnayf_id_sddnayf`)
    REFERENCES `smgyd_suimvm`.`sddnayf` (`id_sddnayf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`medidaintegral_has_sddnayf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`medidaintegral_has_sddnayf` (
  `sddnayf_7_2a` INT NOT NULL,
  `sddnayf_id_sddnayf` INT NOT NULL,
  PRIMARY KEY (`sddnayf_7_2a`, `sddnayf_id_sddnayf`),
  INDEX `fk_nomencladora_has_sddnayf_sddnayf1_idx` (`sddnayf_id_sddnayf` ASC) VISIBLE,
  INDEX `fk_nomencladora_has_sddnayf_nomencladora1_idx` (`sddnayf_7_2a` ASC) VISIBLE,
  CONSTRAINT `fk_nomencladora_has_sddnayf_nomencladora1`
    FOREIGN KEY (`sddnayf_7_2a`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nomencladora_has_sddnayf_sddnayf1`
    FOREIGN KEY (`sddnayf_id_sddnayf`)
    REFERENCES `smgyd_suimvm`.`sddnayf` (`id_sddnayf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smgyd_suimvm`.`medidaexcepcional_has_sddnayf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smgyd_suimvm`.`medidaexcepcional_has_sddnayf` (
  `nomencladora_id_nomenclador` INT NOT NULL,
  `sddnayf_id_sddnayf` INT NOT NULL,
  PRIMARY KEY (`nomencladora_id_nomenclador`, `sddnayf_id_sddnayf`),
  INDEX `fk_nomencladora_has_sddnayf_sddnayf2_idx` (`sddnayf_id_sddnayf` ASC) VISIBLE,
  INDEX `fk_nomencladora_has_sddnayf_nomencladora2_idx` (`nomencladora_id_nomenclador` ASC) VISIBLE,
  CONSTRAINT `fk_nomencladora_has_sddnayf_nomencladora2`
    FOREIGN KEY (`nomencladora_id_nomenclador`)
    REFERENCES `smgyd_suimvm`.`nomencladora` (`id_nomenclador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nomencladora_has_sddnayf_sddnayf2`
    FOREIGN KEY (`sddnayf_id_sddnayf`)
    REFERENCES `smgyd_suimvm`.`sddnayf` (`id_sddnayf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
